### ISSUE TITLE
Failed to start extension

### ISSUE THREAD

**Issue by canperk** [Microsoft/azuredatastudio-postgresql#101]
PGSQL Extension Version: 0.1.0
Azure Data Studio Version: 1.5.1
OS Version: Windows 10, Version 1703 (OS Build 15063.1631)
Steps to Reproduce:

I have installed the extension
After reload I have been notified with "Failed to start Pgsql tools service"

**Comment by akamath46297** [comment]
@canperk could you help with below information:

1. Do you see {users folder}\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.1.0\out\pgsqltoolsservice\Windows\v1.0.0\pgsqltoolsservice\pgtoolsservice_main.exe on your machine?
2. Did you install the extension from Azure Data Studio Marketplace or the GitHub ?
3. Do you have 32 bit or 64 bit OS ?

**Comment by canperk** [comment]
@akamath46297  I have solved this issue with reinstalling extension. Yo can close the issue if my answer convinced you

**Comment by akamath46297** [comment]
I am closing this issue. Please feel free to reopen in case you encounter this issue again
