### ISSUE TITLE
Failed to start Pgsql tools service on MacOS

### ISSUE THREAD

**Issue by maverick915** [microsoft/azuredatastudio-postgresql#108]
- Azure Data Studio Version: 1.4.5 (MacOS 10.13.6)

Steps to Reproduce:

1. Install PostgreSQL extension (v0.1.0) through the Extension Manager (following instructions from https://docs.microsoft.com/en-us/sql/azure-data-studio/postgres-extension?view=sql-server-2017)
2. Restart Azure Data Studio
3. Popup displays in bottom right corner with the message "Failed to start Pgsql tools service".  Expanding the dialog (arrow icon) gives "Source: PostgreSQL (Extension)".

![azure data studio 2019-03-25_12-15-04](https://user-images.githubusercontent.com/18453697/54940154-29b38e80-4ef8-11e9-99b8-4128763cf4a4.png)

There is no additional information in the Output or Problems windows.

After enabling debug logging, I see the following message in the main.log:

[2019-03-25 12:31:01.329] [main] [error] UpdateService error:  Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

**Comment by DigitalDuquette** [comment]
This issue has started for me as well on the latest release of macOS (10.14.5).  The message doesn't error out it hangs at 'Starting pgsql service' 
![Screen Shot 2019-06-07 at 8 29 27 AM](https://user-images.githubusercontent.com/47231954/59104017-62abae80-88fe-11e9-9dfa-7ef4736032cd.png)

I've tried uninstalling and reinstalling the extension.

**Comment by marko-p** [comment]
I'm getting the same error on Windows 10. I do get a PostgreSQL option in the connection sidebar, but I am not able to connect to my PG DB (no error, just endless connection loading).

**Comment by swjain23** [comment]
@maverick915 - Hi, are you still hitting this issue? Can you try the latest version of extension with latest ADS release?

**Comment by gvdncgcg** [comment]
> @maverick915 - Hi, are you still hitting this issue? Can you try the latest version of extension with latest ADS release?

Hi I am still getting "Failed to start Pgsql tools service" when using the Postgresql Extension (0.2.6) with ADS (1.20.1) on a MacOS Catalina 10.15.2

**Comment by maverick915** [comment]
> @maverick915 - Hi, are you still hitting this issue? Can you try the latest version of extension with latest ADS release?

Working now.  Thanks for tagging me on the fix.

**Comment by cvannoy** [comment]
Try installing the mac universal installer. Then right click on the app in finder and select Get Info. Then put a check mark in 'Open Using Rosetta'. I have an Apple M1 Pro chip running Ventura and I've been fighting this all day. This combo worked for me. Link to Universal Installer: https://go.microsoft.com/fwlink/?linkid=2222873

**Comment by MaxKoval1ov** [comment]
Cool, work for me, but it is a little bit confusing that Silicon version doesn't support psql extension.

**Comment by MaxKoval1ov** [comment]
> @MaxKoval1ov Try installing the mac universal installer. Then right click on the app in finder and select Get Info. Then put a check mark in 'Open Using Rosetta'. I have an Apple M1 Pro chip running Ventura and I've been fighting this all day. This combo worked for me. Link to Universal Installer: https://go.microsoft.com/fwlink/?linkid=2222873

Maybe you also have solution for the following error:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/78081544/222422168-d87574cd-356f-48e5-ae8d-73d297c8280b.png">

**Comment by cvannoy** [comment]
@MaxKoval1ov I dont. sorry. good luck.

**Comment by ivatikh** [comment]
Hello!
Anyone has the working solution? Tryed all methods - don't work.

**Comment by denxwan** [comment]
> 

Thanks man this worked for me!
