### ISSUE TITLE
Failed o expand node Error with PostgreSQL 11

### ISSUE THREAD

**Issue by guzmanda** [Microsoft/azuredatastudio-postgresql#109]
Error "Failed to Expand Node" occurs when trying to expand the Functions node in PosgreSQL 11, 

Steps to reproduce:

1) connect to PosgreSQL 11 server
2) expand tree nodes Databases--><schema>-->Functions.

Expected result: no error

Actual result: Error dialog box with message "Failed o expand node".

Note that this error occurs with PosgreSQL 11 but not PosgreSQL 10.

**Comment by akamath46297** [comment]
@guzmanda , thanks for reporting this issue. This is a known issue which is filed https://github.com/Microsoft/azuredatastudio-postgresql/issues/100 . I will close this as duplicate and you can monitor the status on the other bug
