### ISSUE TITLE
PostgreSQL extension not detecting primary keys

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/azuredatastudio-postgresql#110]
- Azure Data Studio Version: 1.5.2

Steps to Reproduce:

1. Connect to a pgsql DB.
2. Try to edit data for a table that does have a primary key assigned.
3. Try to save, but ADS says that there is no column that uniquely identifies the row to be saved (pgadmin does allow such an edit due to the existance of a primary key).

N.B. PostgreSQL text columns are like MSSQL nvarchar(max) columns i.e. they can be used in a WHERE clause.  They can also be marked as a PRIMARY KEY unlike MSSQL. I rely on this a lot.

**Comment by akamath46297** [comment]
@borgdylan , thanks for reporting the issue. Could you share the table schema here ?

**Comment by borgdylan** [comment]
it suffices to have a text column named Id set as a primary key.

**Comment by borgdylan** [comment]
e.g. CREATE TABLE dbo."Test" ("Id" text PRIMARY KEY, "X" integer);

**Comment by borgdylan** [comment]
I think the whole issues stems from the fact that MSSQL service was used as a base and is assuming that a text column cannot have the primary key constraint set on it. For pgsql this assumption is not valid.

**Comment by akamath46297** [comment]
@borgdylan , for above schema you mentioned I was not able to repro this. Would you be able to provide repro steps?

![image](https://user-images.githubusercontent.com/30480046/56926187-f1b6e280-6a85-11e9-9343-94b3820c3725.png)

**Comment by borgdylan** [comment]
I tested again against ADS 1.7.0. It works fine now, so I guess it was a matter of works in progress with v. 1.5.2.
