### ISSUE TITLE
Unhandled exception when table contains non-ascii characters

### ISSUE THREAD

**Issue by marcocitus** [microsoft/azuredatastudio-postgresql#112]
I get an unhandled exception whenever a query returns non-ascii characters.

Query:
```
CREATE TABLE test (
    test text
);
INSERT INTO test VALUES ('hèllo world');
SELECT * FROM test;
```

Messages:
```
4:17:34 AM Started executing query at Line 1
Commands completed successfully
4:17:34 AM Started executing query at Line 4
Commands completed successfully
Unhandled exception while executing query: 'ascii' codec can't encode character '\xe8' in position 27: ordinal not in range(128)
```

**Comment by akamath46297** [comment]
@marcocitus , could you please provide following details: 
1. PostgreSQL version you are trying this on
2. Azure Data Studio Version
3. OS version

I tried to repro this on Windows and I was able to see the results:
![image](https://user-images.githubusercontent.com/30480046/55256602-a4431d80-521a-11e9-9db0-ab2dd4873732.png)

**Comment by marcocitus** [comment]
PostgreSQL version:
``` 
PostgreSQL 11.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609, 64-bit
```

Azure Data Studio version:
```
Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763
````

**Comment by akamath46297** [comment]
@marcocitus , I was not able to repro this on PG 11 as well. I tried to repro this on Windows 10 X64  and able to see the results. Looking at the pgtoolsservice, we use the utf-8 encoding which should take care of this scenario

**Comment by swjain23** [comment]
I was not able to repro this issue with PostgreSQL extension version 0.2.4 and ADS with following info:

Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/36710109/75811027-8cd0b680-5d40-11ea-9194-3e6aa4584b0f.png)

@marcocitus  Are you still seeing this error?

**Comment by swjain23** [comment]
Closing as no repro
