### ISSUE TITLE
pg_dump: aborting because of server version mismatch

### ISSUE THREAD

**Issue by flipchart** [microsoft/azuredatastudio-postgresql#115]
Trying to back up postgres db but get the following error:

```
Backup: pg_dump: server version: 10.6; pg_dump version: 9.6.3
pg_dump: aborting because of server version mismatch
```

I have postgres 10 installed, I assume you've bundled pg_dump 9 with the tool. I couldn't find any way to change the path to pg_dump to the locally installed version (which would be a useful feature). 

Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

PostgreSQL extension v0.1.0

**Comment by petervandivier** [comment]
Same issue here, working around with the below for the moment, although it is context specific depending on local PG server version and OS. 

```powershell
Push-Location '~\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.1.0\out\pgsqltoolsservice\Windows\v1.0.0\pgsqltoolsservice\pg_exes\win\'

Rename-Item 'win' 'win_9.6'

New-Item -Path 'win' -ItemType SymbolicLink -Value 'C:\Program Files\PostgreSQL\10\bin'

Pop-Location
```

ADS appears to read the symlink properly and use the local service binaries.

**Comment by fouadgm** [comment]
Workaround for Mac OS:

```
cd ~/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.6/out/pgsqltoolsservice/OSX/v1.4.0/pgsqltoolsservice/lib/python3.6/pgsqltoolsservice/pg_exes/mac/bin
mv pg_dump pg_dump.bak
mv pg_restore pg_restore.bak
ln -s $(which pg_dump) pg_dump
ln -s $(which pg_restore) pg_restore
pwd
ls -al

cd ../../../../../../pg_exes/mac/bin
mv pg_dump pg_dump.bak
mv pg_restore pg_restore.bak
ln -s $(which pg_dump) pg_dump
ln -s $(which pg_restore) pg_restore
pwd
ls -al
```

Notes:
1. PostgreSQL (pg_dump/pg_restore) should already be installed.
2. Update version in the first cd path as needed - my PostqreSQL extension in ADS is 0.2.6 at the time of posting.

**Comment by battarro** [comment]
Any timeline for this ?

I would like to do backups of remote servers, but the server version mismatch is preventing em from doing so.
![image](https://user-images.githubusercontent.com/10959815/90138275-c58ba780-dd44-11ea-8e5b-c4e83c39fe61.png)

**Comment by battarro** [comment]
I did a work around for this. Basically you match our local pg_dump files to the same binaries that the server has.
The local files are located on
```%userprofile%\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.2.6\out\pgsqltoolsservice\Windows\v1.4.0\pgsqltoolsservice\pg_exes\win```

Get the bins( *.exe and *.bin )  that match your server from 
https://www.enterprisedb.com/download-postgresql-binaries

then the pg dump will work.

**Comment by salvadornava01** [comment]
> I did a work around for this. Basically you match our local pg_dump files to the same binaries that the server has.
> The local files are located on
> `%userprofile%\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.2.6\out\pgsqltoolsservice\Windows\v1.4.0\pgsqltoolsservice\pg_exes\win`
> 
> Get the bins( *.exe and *.bin ) that match your server from
> https://www.enterprisedb.com/download-postgresql-binaries
> 
> then the pg dump will work.

This worked for me! Thank you so much!

**Comment by swjain23** [comment]
Fixed by https://github.com/microsoft/pgtoolsservice/pull/273

**Comment by flipchart** [comment]
@swjain23 Thanks for the PR! So happy to have this resolved.

I did notice though, that you didn't include the tools for postgres 13 which was recently released. Any chance you (or someone else) could add it? Although it looks like you've made it really easy to add new versions as they come out

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
