### ISSUE TITLE
ADS hangs on very large PostgreSQL databases

### ISSUE THREAD

**Issue by FlipperPA** [microsoft/azuredatastudio-postgresql#116]
When connecting to a very large DB server, ADS hangs, eventually giving messages that the window is taking a long time to load, and giving options to reopen the window, continue waiting, or cancel. This happens when trying to browse to ROLES or DATABASES. I've tried clicking continue waiting for over 15 minutes. PGAdmin 4 handles it okay, but I'd love to have the unified interface for both SQL Server and PostgreSQL. 

Our DB contains several hundred schemata, about 60,000 tables, and 20,000 users. It works great when connecting to servers with less large DBs.

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.6.0 and Azure Data Studio v1.47.0. Reopen if this issue is still present, thank you.
