### ISSUE TITLE
Failed to start Pgsql tools service - Win 10

### ISSUE THREAD

**Issue by dphugo** [microsoft/azuredatastudio-postgresql#122]
Installed extension and then get the notification below.
Uninstalled, closed ADS and reinstalled extension as per workaround in Issue #101  with same failure result.
Installed from ADS Marketplace.

**ADS About:**
Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Extension About:**
Name: PostgreSQL
Id: microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.1.0
Publisher: Microsoft

![image](https://user-images.githubusercontent.com/22542589/56881235-0f715100-6a60-11e9-9759-3efc254981d1.png)

**Comment by akamath46297** [comment]
@dphugo could you please check whether you have this path on your Windows 10 machine ?

%UserProfile%\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.1.0\out\pgsqltoolsservice\Windows\v1.0.0\pgsqltoolsservice\pgtoolsservice_main.exe

**Comment by dphugo** [comment]
@akamath46297 Thanks for the quick response. 
I've checked but my path ends here and therefore does not have the exe:
%UserProfile%\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.1.0\out\pgsqltoolsservice\Windows\v1.0.0

**Comment by akamath46297** [comment]
@dphugo , Looks like the extension didn't get downloaded to you system. Could you try following:

1. Close ADS
2. Delete the microsoft.azuredatastudio-postgresql-0.1.0 folder from extensions path
3. Download the extension (VSIX) from https://github.com/Microsoft/azuredatastudio-postgresql/releases/download/v0.1.0/azuredatastudio-postgresql-0.1.0.vsix 
4. Re launch ADS
5. Install the extension by clikcing on File --> Install extension from vsix package . Provide the path to the downloaded vsix 
6. Reload when you see a successful installation of extension message.
7. After reload click o View --> Output . You should see messages related to downloading and installing the extension.
8. After installation try to connect again

If this doesn't work. Could you share the details from output window and also Toggle developer tools from help and errors you might see in the console.

**Comment by dphugo** [comment]
Hi @akamath46297.
I planned to follow the instructions, but saw that after I updated ADS the extension also updated:
![postgreSQL extension update_20190512](https://user-images.githubusercontent.com/22542589/57726286-5cc00600-768f-11e9-91b5-ffae35fe99de.png)

After which everything worked.
Thanks!

**Comment by craibuc** [comment]
I'm having the same issue, albeit with a newer version of ADS.

** Windows**
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎4/‎21/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

**Azure Data Studio**
Version: 1.28.0 (system setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Extension**
Name: PostgreSQL
Id: microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.2.7
Publisher: Microsoft

PostgreSQL is NOT installed on the workstation.  

I did successfully install this extension on the Windows 2012 server that hosts the PostgreSQL DB.
