### ISSUE TITLE
Save as XML does not work for Postgres

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio-postgresql#123]
![image](https://user-images.githubusercontent.com/13777222/57262087-7d4ce800-701f-11e9-8bf9-757533527240.png)

**Comment by akamath46297** [comment]
Yes. This is not yet implemented in Postgres provider

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
