### ISSUE TITLE
(Postgres Plugin) Encoding error while executing queries that have non ascii character results

### ISSUE THREAD

**Issue by asavvop** [microsoft/azuredatastudio-postgresql#124]
While executing a query at a database I get the following when I try to project any collumns that contains values with non-ascii characters. The results are successfully shown in other tools like pgadmin or a console. The error I am getting is the following:

Started executing query at Line 1:
Commands completed successfully
**Unhandled exception while executing query: 'ascii' codec can't decode byte 0xeb in position 0: ordinal not in range(128)**

**Comment by swjain23** [comment]
Duplicate of #112
