### ISSUE TITLE
Hide partitions for partitioned table

### ISSUE THREAD

**Issue by XieJJ99** [microsoft/azuredatastudio-postgresql#126]
Currently all partitions will be displayed, it's better to hide the partitions.
The following statement will filter the partitions:
```sql
 select table_schema,table_name,table_type from  information_schema.tables where table_name not in (     SELECT relname FROM pg_class WHERE  relpartbound IS NOT NULL )
```

**Comment by maurobennici** [comment]
I also need to hide also all the TimeScaleDB hypertable.

**Comment by jonels-msft** [comment]
Reopening, and will close when v0.4 is released.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by jonels-msft** [comment]
Reopening until the fix becomes available for user testing.

**Comment by nasc17** [comment]
Hello, issue has been addressed in our unstable release of PostgreSQL extension v0.4.3-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by XieJJ99** [comment]
Just tried the latest version, the issue is resolved now.
