### ISSUE TITLE
Invalid JSON syntax in the query results

### ISSUE THREAD

**Issue by nvarscar** [microsoft/azuredatastudio-postgresql#130]
When selecting a JSON data type, it would return an incorrectly cased true/false json values. For example
```sql
SELECT '{"a": false, "b": true}'::json
```
would return:
```
{'a': False, 'b': True}
```
but as per [json specification](https://www.json.org/) it should be all lowercase:
```
{'a': false, 'b': true}
```
In addition, the same specification states that the string should be enclosed in double quotes, and it's returned with single quotes. This is not as big of a deal, as modern json processors seems to be mostly fine with it, however, postgresql itself seems to disagree and wouldn't accept single quoted strings:
```
SELECT $${'a': false}$$::json
-- invalid input syntax for type json
```

All in all, this effectively prevents users from using JSON data from the results elsewhere, since the syntax is invalid.

**Comment by swjain23** [comment]
Fixed by microsoft/pgtoolsservice#235
