### ISSUE TITLE
Postgres Azure resources do not appear under the AZURE resources tab

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio-postgresql#134]
Issue Type: <b>Bug</b>

Support connecting to server groups using the Azure resources group. 

![image](https://user-images.githubusercontent.com/41927913/58814975-9c697600-85db-11e9-907f-f20a776399eb.png)

REPO STEPS

1. Create a Postgres resource in Azure
2. Go to ADS
2.1 Under AZURE expand your subscription
- Note that Postgres resources do not appear.

Azure Data Studio version: Azure Data Studio 1.8.0-insider (34bc0efc1c6897e456eb7039d116d60431a9bf85, 2019-06-03T07:13:53.826Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by GaryHopeMS** [comment]
Has related issue for Azure Cosmos DB for PostgreSQL clusters in https://github.com/microsoft/azuredatastudio-postgresql/issues/398

**Comment by nasc17** [comment]
Fixed by Azure Data Studio: https://github.com/microsoft/azuredatastudio/pull/23300

**Comment by nasc17** [comment]
Azure Data Studio v1.45.0 has been released
