### ISSUE TITLE
Citus is not registered as the <Default> database for a Citus Postgres Cluster

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio-postgresql#135]
Issue Type: <b>Bug</b>

STEPS TO REPRODUCTION
1.  Create a new connection to a Citus cluster
2. Enter all the information leaving "Database name" as <Default>
3. Select Connect

NOTE - that an error message is shown suggesting the database name should be postgres 

![image](https://user-images.githubusercontent.com/41927913/58815814-27973b80-85dd-11e9-8bb9-7eb98a335415.png)

Azure Data Studio version: Azure Data Studio 1.8.0-insider (34bc0efc1c6897e456eb7039d116d60431a9bf85, 2019-06-03T07:13:53.826Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by swjain23** [comment]
@gengelbms - This is an error from the server. Your server does not allow connections from this IP address. You need to go to the portal and add a rule to allow connections from this IP.

**Comment by horns-k** [comment]
Could also be related to the fact that in citus cluster default DB is not Postgres but Citus.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/d9f78027-155b-4d57-92c7-2c614f125986)
