### ISSUE TITLE
PostgreSQL option not available in Connection Type dropdown after new installation

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio-postgresql#139]
Similar to #74 - although likely not the exact same issue. Recently a change was made such that ADS doesn't need to reload after installing extensions and so the Provider isn't registered until ADS is restarted. 

At the very least this should be documented in https://docs.microsoft.com/en-us/sql/azure-data-studio/postgres-extension?view=sql-server-2017, although ideally you should have this extension force a reload on installation so that users don't have to go to the docs just to find out.

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.3.1. Reopen if issue persists, thank you.
