### ISSUE TITLE
Unable to browse functions on database

### ISSUE THREAD

**Issue by r4ng3r89** [microsoft/azuredatastudio-postgresql#146]
Issue Type: <b>Bug</b>

After connecting to my local PostGres using the PostGres extension and browsing to the [Functions] folder on my user created data base I get an error:
"Failed to expand node". All the other folders are working except [Functions]

Extension Version 0.2.0

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
