### ISSUE TITLE
EXCEPTION label not color-coded

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio-postgresql#150]
Issue Type: <b>Bug</b>

In the function definition below, I expected the keywork "EXCEPTION" to be in a blue font like the DECLARE, BEGIN and END keywords.

CREATE OR REPLACE FUNCTION somefunc() RETURNS integer AS $$
<< outerblock >>
DECLARE
    quantity integer := 30;
BEGIN
    RAISE NOTICE 'Quantity here is %', quantity;  -- Prints 30
    quantity := 50;
    --
    -- Create a subblock
    --
    DECLARE -- color blue
        quantity integer := 80/0;
    BEGIN -- color blue
        RAISE NOTICE 'Quantity here is %', quantity;  -- Prints 80
        RAISE NOTICE 'Outer quantity here is %', outerblock.quantity;  -- Prints 50
    END;

    RAISE NOTICE 'Quantity here is %', quantity;  -- Prints 50

    RETURN quantity;
EXCEPTION -- color black
    WHEN division_by_zero THEN
        RAISE NOTICE 'caught division_by_zero';
        RETURN 42;
END;
$$ LANGUAGE plpgsql;

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by swjain23** [comment]
Fixed by #232
