### ISSUE TITLE
`SELECT * INTO`  not allowed here

### ISSUE THREAD

**Issue by infraweavers** [microsoft/azuredatastudio-postgresql#151]
Trying to create a backup of a query as a table results in an error:

```
SELECT * INTO my_backup_table FROM table;
```

```
Started executing query at Line 1
SELECT ... INTO is not allowed here
Total execution time: 00:00:00.003
```
This is under version `0.2.1` using Azure Data Studio `1.9.0` against `PostgreSQL 9.5.16 on x86_64-pc-linux-gnu (Debian 9.5.16-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit`

**Comment by kyle-depasquale-renaissance** [comment]
I've encountered this exact issue with a similar command against postgres:
  SELECT
        template_id
        , template_id + 1 AS kpi_template_id
    INTO TEMPORARY template_id_list
    --SELECT *
    FROM (
        VALUES
            (999)
    ) v (template_id);

Azure Data Studio version:
Version: 1.26.0
Commit: 995095f696fd9800e7e621d34daa895d57989ccd
Date: 2021-02-19T03:24:52.069Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
