### ISSUE TITLE
"Go To Definition" does not show function definition

### ISSUE THREAD

**Issue by stepaunov** [microsoft/azuredatastudio-postgresql#152]
"Go To Definition" does not show function definition. 
Function name is full-qualified with user schema.

**Comment by stepaunov** [comment]
[Window Title]
Azure Data Studio

[Main Instruction]
Azure Data Studio

[Content]

Version: 1.9.0
Commit: 78a42e1d112ae3231777722b51eaf44f83ddbe55
Date: 2019-07-10T04:31:36.998Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

[OK] [Copy]

**Comment by stepaunov** [comment]
Name: PostgreSQL
Id: microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.2.1
Publisher: Microsoft

**Comment by jasonverber** [comment]
Same here.

Version: 1.9.0 (user setup)
Commit: 78a42e1d112ae3231777722b51eaf44f83ddbe55
Date: 2019-07-10T04:31:36.998Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
