### ISSUE TITLE
PG SQL Tools Service component exited unexpectedly - Linux

### ISSUE THREAD

**Issue by wenceslau** [microsoft/azuredatastudio-postgresql#154]
Someone can help-me. 

pgsqltoolsservice-linux not work......

**Comment by mcanerizci** [comment]
I'm also getting this error on Manjaro linux and I can't fix it.

**Comment by mhosman** [comment]
Same issue here!

**Comment by swjain23** [comment]
@mcanerizci @mhosman @wenceslau  - Are you still facing the issue? Can you share your extension details? Go to Help -> About and paste the details here.

**Comment by wenceslau** [comment]
In linux you need to install some packages to fix this problem, I don't remember what I do, this was a long time ago, I sorry.

I feeling sad with microsoft because this, they can be solve this problem easily.

**Comment by wenceslau** [comment]
I will find, if I have what I do to solve this problem.

**Comment by swjain23** [comment]
@wenceslau - Hi, we are now actively contributing to this extension and fixing bugs. It will be great if you remember and can share how you fixed this issue. Thank you :)

**Comment by lllauri** [comment]
On Arch I had the same problem, the Output tab showed:
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

The fix was to install libffi6 from AUR.

**Comment by g0josh** [comment]
i had to do this https://github.com/microsoft/azuredatastudio-postgresql/issues/218#issuecomment-695926733

**Comment by LuckyXII** [comment]
> i had to do this [#218 (comment)](https://github.com/microsoft/azuredatastudio-postgresql/issues/218#issuecomment-695926733)

Worked for me!
Running:
Linux 5.9.16-1-MANJARO
Azure Data Studio  1.19.0-2  AUR
microsoft.azuredatastudio-postgresql v0.2.7

**Comment by davidxavier77** [comment]
I am having this issue on Ubuntu 20.04. Seems like ubuntu comes with libffi7. am unable to find a version of libfi6. if anyone has a suggestion i am all ears

**Comment by guillerglez88** [comment]
I had the same issue in Pop os/21.10, had to install libffi7 from apt before following the steps from  https://github.com/microsoft/azuredatastudio-postgresql/issues/218#issuecomment-695926733

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
