### ISSUE TITLE
PostgreSQL Extension: Tables with Declarative Partitions display wrong

### ISSUE THREAD

**Issue by unfilled** [microsoft/azuredatastudio-postgresql#156]
Issue Type: <b>Bug</b>

Hello! 
I have a table with declarative partitionig in it. In Azure Data Studio I don't see the "main" table, but I see all the partitions of this table. 
In pgAdmin, for example, I see the "main" table as a table and its partitions in Partitions section. 
Best Regards.
![ads_postgresql](https://user-images.githubusercontent.com/44000487/62511975-7e183480-b82f-11e9-9872-d83290bd0659.png)

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
