### ISSUE TITLE
Postgres CTE do not work!

### ISSUE THREAD

**Issue by humphrey** [microsoft/azuredatastudio-postgresql#159]
Issue Type: <b>Bug</b>

Postgres CTE (with queries) do not allow data modifying queries.  We cannot run the basic query examples shown at https://www.postgresql.org/docs/10/queries-with.html#QUERIES-WITH-MODIFYING

These examples work fine using `psql` but in Azure Data Studio, give the following error "DECLARE CURSOR must not contain data-modifying statements in WITH"

For example:

```sql
WITH t AS (
    UPDATE products SET price = price * 1.05
    RETURNING *
)
SELECT * FROM t;
```

If I tail my postgres server log, it appears that this extension is re-writing my query to use a cursor rather than running my query as I typed it.  For example:

```sql
DECLARE "9f3d8394-25b6-4c50-8156-f2256ef07d1e" CURSOR WITH HOLD FOR WITH t as (
    UPDATE products SET price = price * 1.05
    RETURNING *
)
select count(*) from t
```

Azure Data Studio version: Azure Data Studio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:12:56.165Z)
OS version: Darwin x64 18.7.0

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.1

</details>

**Comment by BobbyMcWho** [comment]
This is a real pain 😞

**Comment by cocowalla** [comment]
This transparent use of cursors has just resulted in me wasting 2 days tracking down what I thought was a bug 😢

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
