### ISSUE TITLE
Parser does not recognize PostgreSQL bitwise operators ~, << and >>

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio-postgresql#160]
Issue Type: <b>Bug</b>

in ADS, when connected to a PostgreSQL database, this query produces errors:

```
SELECT
    42 & 24 AS "And",
    42 | 24 AS "Or",
    42 # 24 AS "Xor",
    ~1    AS "Negation",
    42 << 1 AS "Left shift",
    42 >> 1 AS "Right shift";

```
Error message:

> syntax error at or near "42"

The same query works fine using psql from the command prompt:

```
postgres=# SELECT
    42 & 24 AS "And",
    42 | 24 AS "Or",
    42 # 24 AS "Xor",
    ~1    AS "Negation",
    42 << 1 AS "Left shift",
    42 >> 1 AS "Right shift";
 And | Or | Xor | Negation | Left shift | Right shift 
-----+----+-----+----------+------------+-------------
   8 | 58 |  50 |       -2 |         84 |          21
```

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gbritton1** [comment]
FWIW I think the problem is the expression `42 # 24` since if I comment that line, the query succeeds

**Comment by sergb213** [comment]
See https://github.com/andialbrecht/sqlparse/issues/539
