### ISSUE TITLE
Cannot run script from file - "No file corresponding to the given URI" error

### ISSUE THREAD

**Issue by stepaunov** [microsoft/azuredatastudio-postgresql#162]
Cannot run PG script from file after upgrading to ADS 1.11.0.

Error:
Execution failed due to an unexpected error: 
Unhandled exception while handling request method query/executeDocumentSelection: "No file corresponding to the given URI"

At the same tme, script successfully executed in New tab, while file not saved yet.

Repro:

1. Open new tab (Ctrl+N) , connect to PosgtreSQL.

2.  Type "select 1;" and Run - success!

3. Save file (Ctrl+S) , reconnect (why it disconnects ??? this is bug too, I suppose) , 
    then try to Run again  - and get error:

   Request query/executeDocumentSelection failed.
  Message: Unhandled exception while handling request method query/executeDocumentSelection: "No file corresponding to the given URI"
  Code: -32603 

--------------------------------------------------------------------------
Extension Info:

Name: PostgreSQL
Id: microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.2.1
Publisher: Microsoft
VS Marketplace Link: undefined?itemName=Microsoft.azuredatastudio-postgresql

Azure Data Studio
Version: 1.11.0
Commit: 460c739a8d90bdbbde39e01abfb8ecdc278ea787
Date: 2019-09-06T18:08:50.974Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by akamath46297** [comment]
This is known issue with new release of ADS https://github.com/microsoft/azuredatastudio/issues/7201. I already have a PR to fix this

**Comment by akamath46297** [comment]
The latest release should fix this. Please try it out https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.2.2

**Comment by ArnieGA** [comment]
This is happening on my end, running version 0.2.7.  Please check on it again.  Thank you.
