### ISSUE TITLE
age function returns number of days instead of '# years # mons # days' (Postgres version 11)

### ISSUE THREAD

**Issue by prasertcbs** [microsoft/azuredatastudio-postgresql#164]
Azure Data Studio
Version: 1.11.0
Commit: 460c739a8d90bdbbde39e01abfb8ecdc278ea787

on PostgreSQL version 11
select age('2019-09-19'::date, '2000-07-11'::date);
return: 7003 days instead of '19 years 2 mons 8 days'

**Comment by gbritton1** [comment]
confirm, at the same query on the same db at the same time, using psql cli returns years months days as expected

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/7e8e6951-bf5b-4c43-8db5-3c1b259374c8)
