### ISSUE TITLE
fe_sendauth: no password (ever) supplied

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azuredatastudio-postgresql#166]
Whenever I re-open a postgres connection, it always gives this error, even though I always check "Remember password" in the UI

![image](https://user-images.githubusercontent.com/969938/65884378-61473b80-e35e-11e9-8de4-540c6236e2ca.png)

**Comment by swjain23** [comment]
@onionhammer - Are you still hitting this issue? What version of extension are you using?

**Comment by onionhammer** [comment]
It looks like this may have been resolved in one of the subsequent releases
