### ISSUE TITLE
Cannot connect to Azure Database for PostgreSQL instance

### ISSUE THREAD

**Issue by gbilodeau** [microsoft/azuredatastudio-postgresql#167]
Create a new connection with the following properties:

Server: bx-shared-test-dev-psql.postgres.database.azure.com
Database: bx-shared-test-dev-db
Port: 5432
User Id: dev@bx-shared-test-dev-psql
Password: [DM if necessary]

When clicking on "Connect", the spinner spins indefinitely and the connection is never established. No errors are displayed, and the Developer Tools console shows no errors either.

A connection can be established using pgAdmin, TablePlus and other GUIs.

**Comment by SimonLuckenuik** [comment]
We are facing the exact same issue.

**Comment by SimonLuckenuik** [comment]
After updating to the new 1.12 release (Oct 2nd 2019), I was to connect to our PostgreSQL database.

**Comment by gbilodeau** [comment]
Upgraded to 1.12 and I'm still experiencing the problem.

**Comment by swjain23** [comment]
@gbilodeau  - Are you still facing this issue? Can you try the latest version of our extension?

**Comment by swjain23** [comment]
Closing as no update.
