### ISSUE TITLE
Empty string incorrectly shown as null in the data grid

### ISSUE THREAD

**Issue by srulandhs** [microsoft/azuredatastudio-postgresql#168]
Postgres SQL v0.2.2

If you run simple SQL statement such as the following, the second column will show as _NULL_ when it should be an empty string. PGAdmin 4 correctly shows the column as an empty string.

Ex: select 1, ''

**Comment by nahk-ivanov** [comment]
Duplicate of #143.

**Comment by DaeunYim** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/143. Closing the issue.
