### ISSUE TITLE
Select with limit cursor error

### ISSUE THREAD

**Issue by robberry** [microsoft/azuredatastudio-postgresql#169]
Issue Type: <b>Bug</b>

When performing a select with limit on a table the following error is experienced:

```
Started executing query at Line 1
cursor "528fe4d3-51b9-49e9-b796-f57d68978481" does not exist
Total execution time: 00:00:00.061
```

Azure Data Studio version: azuredatastudio 1.12.1 (cccb9327c707fe71de24d5ce655acb29cc8946d1, 2019-10-07T21:49:53.568Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by swjain23** [comment]
@robberry - Hi, do you still face this error? I was not able to repro it when running a select query with limit clause.
