### ISSUE TITLE
Exception thrown with Range intersection

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio-postgresql#173]
The query

```SQL
select INT4RANGE(1,5) * INT4RANGE(5,6)
```
Fails with the messages
>Started executing query at Line 1
>Commands completed successfully
>Unhandled exception while executing query: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

CPUs | Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: enabledrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.88GB (4.81GB free)
Process Argv |  
Screen Reader | no
VM | 0%

**Comment by swjain23** [comment]
Fixed by https://github.com/microsoft/pgtoolsservice/pull/231 in pgtoolsservice.
