### ISSUE TITLE
Server panel does not list items

### ISSUE THREAD

**Issue by gkbrown22** [microsoft/azuredatastudio-postgresql#174]
Here's the error:
  Code: -32603 
[Error - 10:02:36 PM] Request connection/listdatabases failed.
  Message: Unhandled exception while handling request method connection/listdatabases: "connection already closed"
  Code: -32603 

But the SQL window still responds. The connection is not closed. 
Using a proxy connection to connect to cloud DB in this case.

**Comment by nahk-ivanov** [comment]
Seems like a duplicate of #99 .

**Comment by swjain23** [comment]
Fixed by microsoft/pgtoolsservice#252
