### ISSUE TITLE
expand dropdown database name

### ISSUE THREAD

**Issue by renatoassis01** [microsoft/azuredatastudio-postgresql#179]
Version: 1.14.1
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:35:43.481Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-74-generic

Steps to Reproduce:
Click on Dropdown Database Name
![image](https://user-images.githubusercontent.com/1714391/72152740-a3830e80-338a-11ea-8fd0-7677e2fb0e98.png)

is too small and makes viewing difficult

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
