### ISSUE TITLE
Support for showing stored procedures in the SERVERS tree

### ISSUE THREAD

**Issue by adavies-btig** [microsoft/azuredatastudio-postgresql#183]
I have a PostgreSQL 12.1 instance that I am connecting to using the latest PostgreSQL extension (v 0.2.2) in Azure Data Studio.  This database contains stored procedures but I do not see them in the SERVER tree view under my database.  Does the extension support stored procedures?  They have been a PostgreSQL feature since v11.

Thanks for any update you can offer.

**Comment by yonisade** [comment]
I was very surprised to see there's no "Procedures" node in this extension.

**Comment by adavies-btig** [comment]
What is the latest update on this request?

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
