### ISSUE TITLE
Error when selecting an array of decimals that includes a NULL

### ISSUE THREAD

**Issue by amachanic** [microsoft/azuredatastudio-postgresql#189]
Tested on v0.2.3

Repro:
SELECT ARRAY[NULL::DECIMAL(28, 0)]

Expected:
[null]

Actual:
Unhandled exception while executing query: Cannot convert None to Decimal

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/4ac53ffa-a0ad-498b-bdb2-b22109e524d6)
