### ISSUE TITLE
row_to_json(..) invalid JSON output

### ISSUE THREAD

**Issue by andreasvatne** [microsoft/azuredatastudio-postgresql#192]
row_to_json(..) outputs an invalid JSON string by using _None_ for _null_ and capitalized boolean values ("False").

`with t(x,y) as (values(false, null::text)) select row_to_json(t) from t`

results in 

`{'x': False, 'y': None}`

while other clients (DataGrip for example) gives this result:

`{"x":true,"y":null}`

**Comment by sergb213** [comment]
Duplicate of #130

**Comment by swjain23** [comment]
Fixed by microsoft/pgtoolsservice#235
