### ISSUE TITLE
PGSQL is hanging often

### ISSUE THREAD

**Issue by Ryukote** [microsoft/azuredatastudio-postgresql#194]
- PGSQL Extension Version: 0.1.0
- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.17763

Azure Data Studio is hanging on simple queries.
These are samples of when it hangs:

1. Run the simple insert query 
2. Try to open a server in a tree view list

In both cases it often hangs and I can't figure out why.
Does Azure Data Studio write logs somewhere?

**Comment by swjain23** [comment]
@Ryukote - Are you still hitting this issue? Also can you share the repro steps.

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
