### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by geserrato** [microsoft/azuredatastudio-postgresql#198]
- Issue Type: `Bug`
- Extension Name: `azuredatastudio-postgresql`
- Extension Version: `0.2.4`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.15.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by swjain23** [comment]
Hi,

What is the problem that you are seeing? Also can you tell us the repro steps.

**Comment by swjain23** [comment]
Closing as no update
