### ISSUE TITLE
Why Aren't Tables Displayed Hierarchically Under Schemas?

### ISSUE THREAD

**Issue by mrcates** [microsoft/azuredatastudio-postgresql#200]
The one thing that's making this extension unusable for me is the fact that tables is one big homogeneous blob of all tables on the database. This would be less challenging if the left sidebar were filterable by keyboard.

What I'd much prefer to see is a tree like so:

```
Schemas
  <Schema1>
    <table1>
    <table2>
    <table3>
  <Schema2>
    <table1>
    <table2>
  <Schema3>
    ...
```

Is there any chance that this is on your roadmap? I'd REALLY REALLY love to use Azure Data Studio as my primiary DB tool, but I'm resigned to datagrip for the time being due to issues like this with browsing large databases

**Comment by luis-enciso** [comment]
This is really important. I also can't navigate on the tables or views within the schemas.

![image](https://user-images.githubusercontent.com/65727490/82583684-be039a80-9b69-11ea-9959-635d45847459.png)

**Comment by speedsrj** [comment]
I am having the same issue, and with this problem we are unable to fully use the tool.

**Comment by Blayvives** [comment]
hello, I have the same problem here, it would be interesting if those responsible for the resource looked more closely at this issue

**Comment by msandipinheiro** [comment]
This issue is extremely important for the project I am participating in. Please, it is possible to find out this question. Thank you.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
