### ISSUE TITLE
Displayed output of binary values in Azure Data Studio isn't any format that postgres accepts

### ISSUE THREAD

**Issue by borland** [microsoft/azuredatastudio-postgresql#204]
Original reference to this stackoverflow question, wherein I was trying to figure out what was going on.
https://stackoverflow.com/questions/60912842/how-can-i-convert-an-escaped-string-to-a-bytea-in-postgresql-is-not-a-binary/60920737#60920737

The issue is as follows:
1. Have a table with some binary (bytea) content in postgresql
2. Query that table in Azure Data Studio
3. Copy/paste the output value of the binary field
4. Attempt to use it in another query (e.g. a select or update)

For example, I have a row with a `bytea` field with the contents `bc6b702a12f8adb482ad517eca5af6407c9f172091242aa79845a17b4d479e2d` (in hex)

If I run `select encode(mycolumn, 'hex') from mytable` then I get the above hex value, which is correct

If I run `select mycolumn from mytable` in `psql` then I get the value `'\xbc6b702a12f8adb482ad517eca5af6407c9f172091242aa79845a17b4d479e2d'` which is also correct - you can see it's the same just with a `\x` on the front.

If I run the exact same `select mycolumn from mytable` in Azure Data Studio then I get the value `b'\xbckp*\x12\xf8\xad\xb4\x82\xadQ~\xcaZ\xf6@|\x9f\x17 \x91$*\xa7\x98E\xa1{MG\x9e-'`

This last one is not any kind of thing that postgres or any of it's conversion functions seem to accept. I haven't been able to figure out thus far how to convert it to a format which is usable.

Could the displayed format in the Results view in Azure Data Studio be updated to use a valid postgresql bytea format please? Preferably hex as that would match what `psql` is doing, but Postgres' `escape` format would be fine too

Kind regards

Orion

**Comment by DaeunYim** [comment]
Not reproducible
