### ISSUE TITLE
After the latest update the "Postgresql" connection type is gone

### ISSUE THREAD

**Issue by derUli** [microsoft/azuredatastudio-postgresql#205]
Version: 1.15.1
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:00:25.531Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-42-generic

After installation of the latest package updates on my Linux machine (runs some Ubuntu derivative)  the "Postgresql" connection type is gone.
The only available connection type is Microsoft SQL.
I reinstalled the plugin but that doesn't fix it.

**Comment by mr-onion-2** [comment]
I've observed the same. I uninstalled v0.2.5 from the marketplace and installed the 0.2.3 release using the .vsix file. I've not tried 0.2.4 as 0.2.3 is working, which is good enough for me for now.

**Comment by lfittl-msft** [comment]
We're reviewing this issue - for now 0.2.4 would be the recommended alternative release to 0.2.5 (0.2.3 is known to have a bug with new Azure Data Studio releases):

https://github.com/microsoft/azuredatastudio-postgresql/releases

**Comment by mr-onion-2** [comment]
Thanks for the quick response. I tried 0.2.4 afterwards but it was giving the same error. Could just be me. Not asking for support though - I'll wait patiently for a 0.2.5/0.2.6 fix.

Couldn't start client pgSQLToolsService

[Error - 11:32:34] Starting client failed
Launching server using command /home/xxx/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.4/out/pgsqltoolsservice/Linux/v1.3.0/pgsqltoolsservice/pgtoolsservice_main failed.

**Comment by lfittl-msft** [comment]
@mr-onion-2 Interesting - does 0.2.2 work for you?

**Comment by swjain23** [comment]
Hi,

I noticed that you are not on the latest version of ADS. We released 1.16.1 recently, can you please update to that and try?

**Comment by mr-onion-2** [comment]
Hi
Good spot. That was the latest version available in the Linux Mint repo. 

Just updated to 1.16.1 and it works perfectly, with the 0.2.5 plugin :) 

Thank you :+1:

**Comment by swjain23** [comment]
Great! I will go ahead and close this issue.
We will also check about the version requirement on the extension.
