### ISSUE TITLE
Postgresql extension no longer working since March update to Azure Data Studio

### ISSUE THREAD

**Issue by johncquayle** [microsoft/azuredatastudio-postgresql#206]
![image](https://user-images.githubusercontent.com/33650781/78097344-882f1900-7438-11ea-9425-434a729c541e.png)

After installing the March update to Azure Data Studio 1.16.1 the Postgresql extension will not work.  I have tried uninstalling and reinstalling the extension, the error message remains the same.

It worked fine before the update.

**Comment by johncquayle** [comment]
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 14, in <module>
  File "D:\a\1\s\pgsqltoolsservice\capabilities\capabilities_service.py", line 15, in <module>
  File "D:\a\1\s\pgsqltoolsservice\query_execution\__init__.py", line 6, in <module>
  File "D:\a\1\s\pgsqltoolsservice\query_execution\query_execution_service.py", line 23, in <module>
ModuleNotFoundError: No module named 'pgsqltoolsservice.query_execution.contracts'
[Error - 4:52:06 pm] Connection to server got closed. Server will not be restarted.

**Comment by mr-onion-2** [comment]
I've observed the same. I uninstalled v0.2.5 from the marketplace and installed the 0.2.3 release using the .vsix file. I've not tried 0.2.4 as 0.2.3 is working, which is good enough for me for now.

**Comment by swjain23** [comment]
@johncquayle  What is the version of PostgreSQL extension that you are using? We released a new version 0.2.5 which is compatible with ADS version 1.16.1. Can you make sure that you have extension version 0.2.5 and ADS version 1.16.1?

**Comment by johncquayle** [comment]
It is the version that is in the extensions store. I tried uninstalling and
reinstalling

**Comment by swjain23** [comment]
Please provide the ADS details. Go to Help -> About and copy the text here.

**Comment by johncquayle** [comment]
Hi,

postgresql 0.2.5
[image: image.png]

ADS
Version: 1.16.1 (user setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Comment by johncquayle** [comment]
installed postgresql 0.2.4 from VSIX and works fine.
update to 0.2.5 breaks it- tried a few times and definitely the case.
Turned off auto-updates for now.

Thanks for the help and suggestions :-)
