### ISSUE TITLE
SQLCMD should be disabled for PG connections

### ISSUE THREAD

**Issue by ptrnecka** [microsoft/azuredatastudio-postgresql#210]
SQLCMD utility is used to execute T-SQL against SQLServer. It cannot be used against PG yet the button to "Enable SQLCMD" is visible/enabled even for PG connections. Clicking the button accidentally fails with unsupported error and it corrupts the opened PG connection (switch to MSSQL).

![image](https://user-images.githubusercontent.com/32365442/78851314-57b62480-79ce-11ea-8ed3-ec29322f5473.png)

Trying to run the query again shows that the connection was corrupted:

![image](https://user-images.githubusercontent.com/32365442/78851379-816f4b80-79ce-11ea-858b-12767e7a7925.png)

**Comment by nasc17** [comment]
Hi could you please update to latest stable release of PostgreSQL extension v0.5.0 and Azure Data Studio v1.45.1. We would appreciate your verification if this issue is still present, thank you.

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.6.0 and Azure Data Studio v1.47.0. Reopen if this issue is still present, thank you.
