### ISSUE TITLE
Select Top 1000 menu command fails

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio-postgresql#216]
Postgresql: PostgreSQL 12.2 on x86_64-apple-darwin19.4.0
VCCode Insiders latest
extension version 0.2.6

Trying to use the Select Top 1000 shortcut menu on a table fails with:

```
[Error - 4:40:20 PM] Request scripting/script failed.
  Message: connection already closed
  Code: 0 
[object Object]
```

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
