### ISSUE TITLE
Can't create a connection to Postgres 12 on port 5433

### ISSUE THREAD

**Issue by chintanp** [microsoft/azuredatastudio-postgresql#221]
I get an error when trying to connect to the Postgres 12 server on my local Windows 10 system. 

> could not parse network address "localhost": Unknown host

![image](https://user-images.githubusercontent.com/752869/83364474-611c9700-a356-11ea-84f1-2eaa90766f7a.png)

I am setting the port to 5433 in the advanced properties: 

![image](https://user-images.githubusercontent.com/752869/83364563-f455cc80-a356-11ea-9cb9-0334f14c9a14.png)

And I tried with several database users. I am able to connect to the database from pgAdmin using the same hostname. 

About my Azure Data Studio:

```
Version: 1.18.1 (user setup)
Commit: 5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa
Date: 2020-05-26T21:14:29.147Z
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

Postgres version:

```
λ postgres --version
postgres (PostgreSQL) 12.0
```

Any help debugging this would be helpful. This is my first time using ADS and the postgres extension.

**Comment by chintanp** [comment]
Worked with using `127.0.0.1` as the IP address in the "Advanced Setting" screen. Closing and leaving this here  for future users.

**Comment by vkg-mca** [comment]
it works, able to connect to the database but get error **Failed to expand node** when click on Databases node

**Comment by vbilopav** [comment]
Just use an IP address instead of a host name, and it works.
