### ISSUE TITLE
PostgreSQL extension not detecting primary keys

### ISSUE THREAD

**Issue by danworley** [microsoft/azuredatastudio-postgresql#222]
When using the PostgreSQL extension in ADS I'm unable to get visibility into the primary keys on my tables. Either in the connections explorer view. Or when I use the `Script as Create` command. Steps to reproduce:

1. Create table with a primary key.
```
CREATE TABLE IF NOT EXISTS foo (
	foo_id INT PRIMARY KEY,
	foo_name TEXT);
```
2. Browse to the table using connections explorer and verify that in table public.foo there are no constraints or indexes related to `foo_id`
3. Right click on the table name public.foo and select `Script as Create`
4. Verify that the script created does not create a primary key. Example output:
```
CREATE TABLE public.foo
(
    foo_id integer NOT NULL,
    foo_name text COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

**Comment by swjain23** [comment]
Hi,

We are able to repro the bug and will take a look at it.
