### ISSUE TITLE
Cannot backup from Azure PostgreSQL

### ISSUE THREAD

**Issue by mflps** [microsoft/azuredatastudio-postgresql#223]
Hi I'm trying to backup, but I receive this error:
Backup: pg_dump: server version: 10.11; pg_dump version: 9.6.3
pg_dump: aborting because of server version mismatch

**Comment by swjain23** [comment]
Duplicate of #115

**Comment by DaeunYim** [comment]
Fixed by https://github.com/microsoft/pgtoolsservice/pull/273
