### ISSUE TITLE
Installing extension for all Windows users

### ISSUE THREAD

**Issue by cat-mucius** [microsoft/azuredatastudio-postgresql#224]
Hi,

Is it possible to install the PostgreSQL extensions for all users of Windows machine?
As I see, it's being installed into `%USERPROFILE%\.azuredatastudio\extensions`, meaning that every user is supposed to install it separately.

I need to prepare a WVD ([Windows Virtual Desktop](https://azure.microsoft.com/en-us/services/virtual-desktop/)) image (for desktop virtualization) with this extension already in place for all users. Is this achievable?

**Comment by swjain23** [comment]
Did you use system installer for the Azure Data Studio? I think it might work if you use system installer instead of User installer: https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15

**Comment by cat-mucius** [comment]
I definitely used the system installer, `azuredatastudio-windows-setup-1.18.1.exe`.
The Studio is installed into `C:\Program Files\Azure Data Studio`.

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.6.0 and Azure Data Studio v1.47.0. Reopen if this issue is still present, thank you.
