### ISSUE TITLE
Can't Script As Create Views

### ISSUE THREAD

**Issue by mosqueteiro** [microsoft/azuredatastudio-postgresql#226]
I am not able to use the _Script As Create_ to see the query that makes up a view

```
[object Object]
[Error - 2:22:03 PM] Request scripting/script failed.
  Message: syntax error at or near "FROM"
LINE 20: FROM pg_class c
         ^

  Code: 0 
```

### Azure Data Studio
Version: 1.19.0
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:03:19.036Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
PostgreSQL extension: 0.2.6

### Server
GCP Cloud SQL
Postgres 11

---

from server logs

> ERROR:  syntax error at or near "FROM" at character 620
> STATEMENT:  SELECT
> c.oid,
> c.xmin,
> (CASE WHEN length(spc.spcname) > 0 THEN spc.spcname ELSE 'pg_default' END) as spcname,
> c.relname AS name,
> nsp.nspname AS schema,
> description AS comment,
> c.reltablespace AS spcoid,
> pg_get_userbyid(c.relowner) AS owner,
> pg_get_viewdef(c.oid, true) AS definition,
> array_to_string(c.relacl::text[], ', ') AS acl,
> CASE WHEN 18312 <= 13711 THEN True ELSE False END AS system_view,
> (SELECT
> array_agg(provider \|\| '=' \|\| label)
> FROM
> pg_seclabels sl1
> WHERE
> sl1.objoid=c.oid AND sl1.objsubid=0
> ) AS seclabels,
> FROM pg_class c
> LEFT OUTER JOIN pg_namespace nsp on nsp.oid = c.relnamespace
> LEFT OUTER JOIN pg_tablespace spc on spc.oid=c.reltablespace
> LEFT OUTER JOIN pg_description des ON (des.objoid=c.oid and des.objsubid=0 AND des.classoid='pg_class'::regclass)
> WHERE ((c.relhasrules
> AND
> (EXISTS(
> SELECT
> r.rulename
> FROM
> pg_rewrite r
> WHERE
> ((r.ev_class = c.oid) AND (bpchar(r.ev_type) = '1'::bpchar))
> ))
> ) AND (c.relkind = 'v'::char))
> AND c.oid = 18312::oid

**Comment by mosqueteiro** [comment]
_Script As Create_ seems to work fine for tables

**Comment by mosqueteiro** [comment]
It looks like there is an extra comma in this query. Hope this helps the trouble shooting

> sl1.objoid=c.oid AND sl1.objsubid=0
> ) AS seclabels,
> FROM pg_class c
> LEFT OUTER JOIN pg_namespace nsp on nsp.oid = c.relnamespace

**Comment by swjain23** [comment]
@mosqueteiro - We are looking at it, thank you for the detail.

**Comment by swjain23** [comment]
Fixed by https://github.com/microsoft/pgtoolsservice/pull/254

Will be part of next release.
