### ISSUE TITLE
Cannot expand functions list (again)

### ISSUE THREAD

**Issue by mosqueteiro** [microsoft/azuredatastudio-postgresql#227]
The Functions list is not showing anything and when refreshing an error is thrown.
#100  stated this issue was solved in **v0.2.2**, however I am running into this issue again on **v0.2.6**

### Local config
**client OS:** macOS Catalina version 10.15.5
**Azure Data Studio**
**Version:** 1.19.0
**Commit:** 4095037f2578c23033867e611e82c13de114ca5a
**Date:** 2020-06-11T22:03:19.036Z
**VS Code:** 1.46.0
**Electron:** 7.2.4
**Chrome:** 78.0.3904.130
**Node.js:** 12.8.1
**V8:** 7.8.279.23-electron.0
**OS:** Darwin x64 19.5.0 
**PostgreSQL extension:** 0.2.6

### Sever config
**GCP Cloud SQL**
PostgreSQL 11

---

The visual error from Azure Data Studio is
> Error
> Failed to expand node

and from the server error logs:

> ERROR: column "proisagg" does not exist at character 668
> HINT: Perhaps you meant to reference the column "pr.prolang"
> STATMENT:
> SELECT
> pr.oid,
> pr.proname \|\| '(' \|\| COALESCE(pg_catalog.pg_get_function_identity_arguments(pr.oid), '') \|\| ')' as name,
> lanname,
> pg_get_userbyid(proowner) as funcowner,
> description,
> nsp.nspname AS schema,
> nsp.oid AS schemaoid,
> CASE
> WHEN nsp.nspname like 'pg_%' or nsp.nspname = 'information_schema'
> THEN true
> ELSE false END as is_system
> FROM
> pg_proc pr
> INNER JOIN
> pg_namespace nsp ON pr.pronamespace= nsp.oid
> JOIN
> pg_type typ ON typ.oid=prorettype
> JOIN
> pg_language lng ON lng.oid=prolang
> LEFT OUTER JOIN
> pg_description des ON (des.objoid=pr.oid AND des.classoid='pg_proc'::regclass)
> WHERE
> proisagg = FALSE
> AND typname NOT IN ('trigger', 'event_trigger')
> ORDER BY
> proname;

**Comment by swjain23** [comment]
@mosqueteiro - We are investigating the issue.

**Comment by swjain23** [comment]
Was able to repro on Mac for PG version >= 11. No issues on windows.

**Comment by nasc17** [comment]
Latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
