### ISSUE TITLE
Unable to start extension

### ISSUE THREAD

**Issue by LanceLockwood** [microsoft/azuredatastudio-postgresql#231]
![image](https://user-images.githubusercontent.com/35380183/86396895-6c6e2580-bc68-11ea-9e20-266bc1dfca8e.png)
Was able to use to extension and all of a sudden I'm not able to. I keep getting "Couldn't start client pgSQLToolsService". 

I've tried reinstalling extension and reinstalling data studio with no luck.

Any thoughts?

**Comment by Aaronmyster** [comment]
Same here. I've also tried uninstalling and reinstalling several versions of the extension. I've also tried running ADS as an administrator. No luck on windows 10. Just "Launching server using command ...pgtoolservice_main.exe" failed.

**Comment by LanceLockwood** [comment]
@Aaronmyster Mine started working. No explanation as to why though. Had honestly given up on it but gave it a shot one day just to check. Also windows 10.

**Comment by swjain23** [comment]
@Aaronmyster - Are you still facing the issue? Can you share the ADS version details (Help -> About) and the PG extension version?

**Comment by Aaronmyster** [comment]
I re-installed ADS and the extension again a few days ago and it worked just fine. It looks like i have the same versions of everything. Strange. Thanks for checking!
