### ISSUE TITLE
Fundamental Requirements

### ISSUE THREAD

**Issue by swjain23** [microsoft/azuredatastudio-postgresql#233]
This issue is to track the fundamental requirements for GA:

- [ ] Telemetry and Privacy
- [ ] Reliability
- [ ] Acquisition 
- [ ] Release, Pipelines and Build 
- [ ] Localization 
- [ ] Accessibility 
- [ ] Security 
- [ ] UX & Branding 
- [ ] Quality Testing
- [ ] Performance Testing
- [ ] Documentation

**Comment by mksuni** [comment]
Closing this issue as not action from product side
