### ISSUE TITLE
Error while trying to install postgreSQL extension on Azure studio 

### ISSUE THREAD

**Issue by NidhiArien** [microsoft/azuredatastudio-postgresql#235]
Trying to install postgreSQL in Azure data studio and getting this error:

Unable to install extension 'microsoft.azuredatastudio-postgresql' as it is not compatible with Azure Data Studio '1.14.0'.

Azure Data Studio details:
Version: 1.14.1
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:37:56.865Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mksuni** [comment]
@NidhiArien  I could not reproduce the issue. Please re-poen the issue if the problem still persists
