### ISSUE TITLE
Save to CSV file has extra new lines after every row

### ISSUE THREAD

**Issue by joshuahomer** [microsoft/azuredatastudio-postgresql#238]
When you run a query and save the results to a CSV file, there are extra new lines after every row (see attached image). Depending on who is parsing the CSV file this can cause problems. For example, in Excel it will have empty rows between the data (see attached image).
![image](https://user-images.githubusercontent.com/25203652/89460323-f48b9300-d71e-11ea-9242-5824b3eebc21.png)
![image](https://user-images.githubusercontent.com/25203652/89460398-12f18e80-d71f-11ea-8788-50bdea5a7644.png)

**Comment by amerilife-pace** [comment]
Please note that this is still occurring and people are interested in a fix

**Comment by barrank** [comment]
This is already happening!
Also, PostgreSQL queries are ignoring the separator specified in settings.

![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/6878598/8c814407-5e28-4eb1-a9b4-259a4931d16d)

![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/6878598/8a8e1d29-b33d-4a34-b8c6-85f11b39934d)
