### ISSUE TITLE
Script: GENERATED IDs not scripted correctly (v10.x)

### ISSUE THREAD

**Issue by ps2goat** [microsoft/azuredatastudio-postgresql#240]
PG 10.x allows us to define something similar to SQL Server's Identity type column, preventing insertion, auto-incrementing, etc., without having to reference a sequence.

When a table is scripted as Create, my table only has an `int` for the id field's type.

Azure Data Studio + extension script:

```CREATE TABLE public.errors
(
    id integer NOT NULL,
    description "character varying(100)" COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.errors
    OWNER to postgres;
```

pgAdmin 4.19 script:
```
-- Table: public.errors

-- DROP TABLE public.errors;

CREATE TABLE public.errors
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(100) COLLATE pg_catalog."default"
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.errors
    OWNER to postgres;
```

And just for reference, my original creation script:

```
create table errors (
    id int generated always as identity,
    description varchar(100)
);
```

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.5.0. Please reopen if issue is still present, thank you.
