### ISSUE TITLE
PostgreSQL extension - unexpected error.

### ISSUE THREAD

**Issue by brett-baker-dynata** [microsoft/azuredatastudio-postgresql#242]
After executing and stopping a query, a subsequent execution results in

Execution failed due to an unexpected error: 
	Another query is currently executing.
Total execution time: 00:00:00

Verified that the query is not running.

**Comment by f1crazed** [comment]
@brett-baker-dynata I was able to fix the issue by uninstalling the extension, restart Azure Data Studio and then reinstall the extension.
