### ISSUE TITLE
Editdata: Revert row does not work.

### ISSUE THREAD

**Issue by praveenbarli** [microsoft/azuredatastudio-postgresql#25]
**Repro steps:**

Open a table in edit data mode.
Place cursoner in  last row(ie, with NULL entries), second column 
Enter a value
Now place the cursor in left border of this row, right click and select "Revert"
Row values are not reverted.
Sometimes this error is shown: "Update cell failed: list index out of range"

**Expected**: 
Row values should get reverted and show NULL again

**Comment by nasc17** [comment]
Hello, issue has been addressed in our unstable release of PostgreSQL extension v0.4.3-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.5.0. Please reopen if issue is still present, thank you.
