### ISSUE TITLE
Internal exception when querying timestamp from BC

### ISSUE THREAD

**Issue by jeffmccormick** [microsoft/azuredatastudio-postgresql#250]
**Issue**
Postgres happily stores timestamps back to ~4000 BC, however when that data is queried an unhandled exception occurs stating
> Unhandled exception while executing query: year -1 is out of range

(in this case, the timestamp is in the year 2 BC)

**Expected result**
BC timestamps are properly handled and displayed

**Minimal repro**

    CREATE TABLE bc_timestamp_test (t timestamp);
    INSERT INTO bc_timestamp_test (t) VALUES ('2-01-01 BC');
    SELECT t FROM bc_timestamp_test;

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by jeffmccormick** [comment]
Can confirm this is fixed in v0.5.1!
