### ISSUE TITLE
Cannot format documents when connected in PostgreSQL database

### ISSUE THREAD

**Issue by gcapnias** [microsoft/azuredatastudio-postgresql#251]
Azure Data Studio v1.24.0 (user setup)
PostgreSQL extension: v0.2.7
pgToolsService v1.5.0

When I upgraded to the latest edition of Azure Data Studio - document formatting while connected to a PostgreSQL database, does not work.

On output window, for ossdbToolsService I get the error:

> It seems the debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py
> This may make the debugger miss breakpoints in the standard library.
> Related bug: https://bugs.python.org/issue1180193

Any ideas? Suggestions?

Thanks,
George J.

**Comment by robbohn** [comment]
I get the same issue:
> It seems the debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py
> This may make the debugger miss breakpoints in the standard library.
> Related bug: https://bugs.python.org/issue1180193
> [Error - 4:15:19 PM] Request scripting/script failed.
>   Message: could not decorrelate subquery
> 
>   Code: 0 
> [object Object]

Azure Data Studio v1.25.1 (system setup)
PostgresSQL extension 0.2.7
PostgresSQL database download 13.1 (64-bit) from https://www.enterprisedb.com/downloads/postgres-postgresql-downloads

**Comment by teo113** [comment]
Same here
`It seems the debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
[Error - 16:00:58] Request metadata/list failed.
  Message: Unhandled exception while listing metadata: cursor already closed
  Code: 0 `

Azure Data Studio: 1.27.0 (system setup)
Local machine: Windows 10 64bit
Local python install: 3.9.2 64bit (if that matters?)
PostgresSQL extension: 0.2.7
However, I don't know if this error is related to my PostgreSQL extension or not (I'm new to Azure Data Studio).

**Comment by gcapnias** [comment]
Un update on this issue:

- When connecting to database and application presents the tables of the database, If I select 'New query' from the top, and begin to write a new query, code-formating works!
- Then if you save and close the query, and re-open the file, it does not.

What seems to make the difference is the SQL Language Provider, on the first case it is PGSQL, on the second case none is chosen, user cannot change the provider - it comes with the message: 'A connection using engine PGSQL exists. To change please disconnect or change connection'.

Can someone re-produce the behavior?

Should saved queries for PostgreSQL have a certain extension in order to be identified in order PGSQL Language Provider used?


Regards,
George J.

**Comment by marko-p** [comment]
I'm also getting this error.

Azure Data Studio:
Version: 1.28.0 (user setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363 (That's Windows 10, x64, version 1909)
PostgresSQL extension: 0.2.7

**Comment by davidnjohansson** [comment]
I can confirm this is a issue.

If creating a new query by selecting the database then "New Query", Azure Data Studio automatically picks up PGSQL. So this is working.

What's not working is if I open an already existing file, it doesn't pick up PGSQL. If I try to choose it I receive _"A connection using engine PGSQL exists. To change please disconnect or change connection"_

Version: 1.29.0 (system setup)
Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
Date: 2021-05-15T01:12:11.112Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043
