### ISSUE TITLE
New PostgreSQL ADS extension crashes 

### ISSUE THREAD

**Issue by likamrat** [microsoft/azuredatastudio-postgresql#252]
###Environment details
Version: 1.24.0
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

microsoft.azuredatastudio-postgresql extension
0.2.7

###Error
OSS DB Tools Service component exited unexpectedly. Please restart Azure Data Studio.

###Impact
Cannot open connection to Azure Arc postgresql instance (DB is up and running).
Restarting ADS and uninstall/install extension does not solve the issue.

**Comment by dmc-tech** [comment]
I get the same error.  VCRUNTIME140.DLL is missing. You can resolve by installing the 64 bit version of the Visual C++ 2015 Redistributable.
https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by likamrat** [comment]
Thx @dmc-tech that did the trick. I will test it with the automation

**Comment by gcapnias** [comment]
I have the same problem, but I cannot install v14.0.24123 - I have already installed v14.0.24215!

Does it need only v14.0.24213?


Thanks,
George J.

**Comment by nasc17** [comment]
Latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
