### ISSUE TITLE
New PostgreSQL Project doesn't work

### ISSUE THREAD

**Issue by yunuskiran** [microsoft/azuredatastudio-postgresql#254]
New PostgreSQL Project Menu Item giving error 

command 'pgproj.add.new' not found: Error: command 'pgproj.add.new' not found

"../resources/app/out/vs/workbench/workbench.desktop.main.js:5592:451 [<root>]"

**Comment by yualan** [comment]
Hi @yunuskiran, we were unable to repro, please respond back if this continues to be an issue
