### ISSUE TITLE
Syntax highlighting on TRUNC() function

### ISSUE THREAD

**Issue by pdbenbow** [microsoft/azuredatastudio-postgresql#261]
The TRUNC() function works fine, but the syntax highlighting is wrong. It's showing as white text (using dark mode) when it should be the same color as other functions like ROUND() and SUM().

![image](https://user-images.githubusercontent.com/13852613/111681332-7f765500-87f9-11eb-9e35-e99d3eb56549.png)

Postgres extension is v0.2.7

```
Version: 1.27.0 (user setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
