### ISSUE TITLE
Save as CSV ignores delimiter option

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio-postgresql#262]
When the setting is set to:

![image](https://user-images.githubusercontent.com/54043604/112363770-18dab680-8c93-11eb-96f8-06783aea92ce.png)

And I try to save as a CSV, the CSV file uses ',' instead of the one defined on the settings.

![image](https://user-images.githubusercontent.com/54043604/112364047-5e977f00-8c93-11eb-94bb-2f80ee3a9a61.png)

PS: I was not sure if this is the correct place, correct me if I am wrong.

**Comment by gtsalmas** [comment]
Hi,

I am facing the same issue. In my case, the setting is as follows and I keep getting comma-separated values.

"queryEditor.results.saveAsCsv.delimiter": ";"

Thank you!

**Comment by nasc17** [comment]
Hello, issue has been addressed in our unstable release of PostgreSQL extension v0.4.3-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.5.0. Please reopen if issue is still present, thank you.
