### ISSUE TITLE
OSS DB Tools - Error

### ISSUE THREAD

**Issue by klaud-ctrl** [microsoft/azuredatastudio-postgresql#266]
Hi there, Im running into an error and I cant connect to my pg server on azure. Can you help out here?

![screenshot](https://user-images.githubusercontent.com/55669588/113697335-57c92d00-96d3-11eb-8c5b-c2625027af3a.png)

**Comment by iFoton** [comment]
Got same issue. Windows Server 2019.

**Comment by iFoton** [comment]
There is [solution](https://github.com/microsoft/azuredatastudio-postgresql/issues/252). In brief you have to install Microsoft Visual C++ 2015 Redistributable Update 3 RC.

**Comment by DaeunYim** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/252. Closing the issue.
