### ISSUE TITLE
Bug in syntax when selecting top 1000 from a materialized view

### ISSUE THREAD

**Issue by bergeron** [microsoft/azuredatastudio-postgresql#270]
The issue is described here: https://github.com/microsoft/azure_arc/issues/498

When selecting top 1000 from a materialized view, the query is missing a space between the column name and `from`.  I reproduce the problem on PostgreSQL extension v0.2.7 + ADS version 1.28.0.

**Comment by bergeron** [comment]
I expect this would be fixed here:

https://github.com/microsoft/pgtoolsservice/blob/1f50d541bfd5798936d12a4d6c500dad578f2a72/pgsmo/objects/view/materialized_view_templates/pg/9.3_plus/select.sql

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
