### ISSUE TITLE
Refreshing is not working after creating new tables

### ISSUE THREAD

**Issue by Zaniyar** [microsoft/azuredatastudio-postgresql#277]
Issue Type: <b>Bug</b>

After creating a table with queries, the table is not shown in the left bar view (connections) - even refresh is not helping. you need to disconnect and reconnect.

Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19042

**Comment by ps2goat** [comment]
This also doesn't work when modifying tables, such as adding or dropping columns. It doesn't matter at which level you try to refresh-- the columns folder, the table, the tables folder, the database-- none of them work.
