### ISSUE TITLE
Unhandled exception while executing query: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)

### ISSUE THREAD

**Issue by tobiulm** [microsoft/azuredatastudio-postgresql#278]
I get this error on my Win Box (Win 21H1 Build(19043.1052) , Linux Box (Fedora 34) and macOS (BigSur 11.4) Box when I try to make this simple sql select statement to my postgresql db (postgres (PostgreSQL) 9.3.25) on synology nas (DSM 6.2.4-25556):`select * from customers`
The Output is: `Started executing query at Line 1
Commands completed successfully
Unhandled exception while executing query: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)
Total execution time: 00:00:00.030`

I use this sample db because a lot of my students are familiar with northwind database [https://github.com/pthom/northwind_psql](url)

**Comment by DaeunYim** [comment]
Not reproducible..
