### ISSUE TITLE
No proper error in postgres

### ISSUE THREAD

**Issue by sree-prakkash** [microsoft/azuredatastudio-postgresql#283]
Issue Type: <b>Feature Request</b>

When trying to create a new function in postgres, the error message is not proper and it is not showing exact line where the error is thrown. Instead of that error line is showing as 1. This is frustrated for developers while creating a function/execuing the queries.

Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19042

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
