### ISSUE TITLE
does not support autocompletion on database column names

### ISSUE THREAD

**Issue by findtravishere** [microsoft/azuredatastudio-postgresql#288]
Issue Type: Feature Request

When typing queries in, Azure DS does not detect the column names on auto completion unlike querying Postgres on VSCode. 

VSCode
![image](https://user-images.githubusercontent.com/63047970/130342469-d7193fbd-220b-40d8-aa16-9ddf2756acd1.png)

Azure DS
![image](https://user-images.githubusercontent.com/63047970/130342475-41b8c6bb-94d0-4b9a-b5e3-1668f19ebdb7.png)

Azure Data Studio Version: 1.32.0
OS: MacOS Big Sur 11.4 / Darwin x64 20.5.0

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
