### ISSUE TITLE
Funding / Support

### ISSUE THREAD

**Issue by hub-il** [microsoft/azuredatastudio-postgresql#289]
Is this extension still being developed by Microsoft?  It has been almost a year since the last release.  We will look elsewhere for a PostgreSQL development environment if the answer is no.

**Comment by mksuni** [comment]
@hub-il  we are evaluating all the issues for this extension. I shall post details here when we have a timeline for fixes.

**Comment by jonsagara** [comment]
Hello,

Have you been able to create the timeline for fixes?

Thank you,

Jon

**Comment by nasc17** [comment]
Hello, this extension is currently being updated with monthly releases. Please upgrade to latest stable release of PostgreSQL extension v0.4.2.
