### ISSUE TITLE
Not creating a new connection when server is the same but port is different 

### ISSUE THREAD

**Issue by nekk29** [microsoft/azuredatastudio-postgresql#296]
Issue Type: <b>Bug</b>

Azure data studio is updating an existing connection when I create one with the same server but different port, it is supposed to create a new connection but it's updating an existing connection, I haven't found if it this an azure data studio issue or if it is the postgres extension

Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nasc17** [comment]
Similar to https://github.com/microsoft/azuredatastudio-postgresql/issues/113
Can you please install latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
