### ISSUE TITLE
Can no longer connect to PostgreSQL in ADS on MacBook M1

### ISSUE THREAD

**Issue by alexepperly** [microsoft/azuredatastudio-postgresql#301]
I was able to use my local PostgreSQL connection in ADS just fine the first time I established it. However, after closing and reopening ADS, it no longer connects, and just sits there forever trying to establish a connection with the wheel spinning. It also gives me this error message when ADS opens:

**_[Error - 10:45:48 AM] Starting client failed
Launching server using command /Users/[user name]/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.7/out/ossdbtoolsservice/OSX/v1.5.0/pgsqltoolsservice/ossdbtoolsservice_main failed._**

I am using ADS using Docker on a MacBook Pro M1.  I am able to use MSSql server on ADS just fine, it's only Postgres with ADS that doesn't work.  PGS still works fine in PG Admin.  I have already tried deleting the PG extension and reinstalling it, both manually and through the extension browser.  I have tried restarting my computer, restarting ADS, and every combination of uninstalling and reinstalling I can think of. I don't know why it would work once and then no longer work again.

Thanks for your help. 

EDIT: I have tried changing the server name from localhost to 127.0.0.1 as another user suggested, I have tried entering the port number 5432 manually, and I know my username and PW are correct (I am using them in PGAdmin). I have made sure my PGAdmin is not open at the same time, and I even deleted the MSSql connection and restarted it to make sure it wasn't interfering.

**Comment by dtsao** [comment]
I had the same issue except on Windows 10 starting about 2 weeks ago.  After ADS opens, I got:

[Error - 6:25:29 PM] Starting client failed
Launching server using command c:\Users\user\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.2.7\out\ossdbtoolsservice\Windows\v1.5.0\pgsqltoolsservice\ossdbtoolsservice_main.exe failed.

After updating to the latest ADS update, the problem went away!

Version: 1.35.0 (user setup)
Commit: e9c8eb8564f537726b36b5f15c7f35e62f229284
Date: 2022-02-23T17:36:02.883Z (1 day ago)
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by ajstewart** [comment]
I was wondering if PostgreSQL support on Apple Silicon was still on the to do list for ADS? The Pgsql tools service fails to start on the native Silicon version and I still have to resort to using Rosetta.

I was following #20775 which I noticed was closed so was wondering what is the status.

**Comment by aheld** [comment]
> I was following [#20775](https://github.com/microsoft/azuredatastudio/issues/20775) which I noticed was closed so was wondering what is the status and saw this issue was linked.

I tried the insiders version that was post that merge, still broken for me in the same way.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/217864/229370688-56de917c-05ba-44c1-ab75-869be9dac866.png">

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/356. Closing the issue
