### ISSUE TITLE
Save As Excel not working

### ISSUE THREAD

**Issue by BraveThrasher** [microsoft/azuredatastudio-postgresql#314]
Issue Type: <b>Bug</b>

**Steps to reproduce:**
1. Write and execute a simple query
2. On the right side of the results panel click the icon for "Save As Excel"
3. In the "Choose Results File" window use the default proposed filename "Results.xlsx" and click the "Save" button.
4. "Saving file..." notification appears

**Result:**
An empty file of 0 bytes is created and that is all. The notification stays visible and for the rest nothing happens.

**Expected result:**
A true Excel file is created with the result of the executed query.

**Information:**
Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|
</details>

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
