### ISSUE TITLE
Show rows affected by updates

### ISSUE THREAD

**Issue by brendanlong** [microsoft/azuredatastudio-postgresql#315]
When running a query against SQL Server, Azure Data Studio shows the number of rows affected after an UPDATE finishes:

![image](https://user-images.githubusercontent.com/1447206/160647711-8e2ad4d7-5724-49a3-9ff4-2e84737c470b.png)

But against PostgreSQL, we only get "Commands completed successfully":

![image](https://user-images.githubusercontent.com/1447206/160647913-15a4e5da-22ec-4af7-80b4-5ef31511646e.png)

(Images are from [this StackOverflow question asking for the same feature](https://stackoverflow.com/questions/67053002/azure-data-studio-does-not-display-the-rows-affected-for-update-statements))

Postgres should be returning the number of rows affected by updates in the [CommandComplete tag](https://www.postgresql.org/docs/current/protocol-message-formats.html):

> For an INSERT command, the tag is INSERT oid rows, where rows is the number of rows inserted. oid used to be the object ID of the inserted row if rows was 1 and the target table had OIDs, but OIDs system columns are not supported anymore; therefore oid is always 0.
> 
> For a DELETE command, the tag is DELETE rows where rows is the number of rows deleted.
> 
> For an UPDATE command, the tag is UPDATE rows where rows is the number of rows updated.
> 
> For a SELECT or CREATE TABLE AS command, the tag is SELECT rows where rows is the number of rows retrieved.
> 
> For a MOVE command, the tag is MOVE rows where rows is the number of rows the cursor's position has been changed by.
> 
> For a FETCH command, the tag is FETCH rows where rows is the number of rows that have been retrieved from the cursor.
> 
> For a COPY command, the tag is COPY rows where rows is the number of rows copied. (Note: the row count appears only in PostgreSQL 8.2 and later.)

Interestingly, we _do_ get rows affected if we return a value, like `UPDATE ... RETURNING id`, but that's not ideal when you're updating large numbers of rows. It seems like however this plugin works, it only returns rows affected when the response is SELECT-like.

**Comment by gcapnias** [comment]
I do believe this is a feature missing from the extension. The number of rows affected by the SQL query should me returned in the messages windows.


George J.

**Comment by nasc17** [comment]
Hello, we would appreciate your verification if this issue is still present in latest unstable release of PostgreSQL extension v0.4.3-insiders.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/7000ed31-b42b-47c3-9e40-aca1563e3e0e)
