### ISSUE TITLE
Issues in installing the PostgreSQL extension on Azure Data Studio

### ISSUE THREAD

**Issue by sivakumaraz** [microsoft/azuredatastudio-postgresql#319]
Hello,

I installed the Azure Data Studio (azuredatastudio-windows-setup-1.35.1) on Windows server 2019.
I also downloaded the VSIX file and installed the PostgreSQL extension using Azure Data Studio Palette (azuredatastudio-postgresql-0.2.7-win-x64) to connect with the PostgresSQL DB. 
<img width="362" alt="PostgreSQL Error" src="https://user-images.githubusercontent.com/104864272/166553060-9eebe6a1-1772-4cc6-b6c4-5c8ba9406b69.png">

Once I followed the above steps, I am getting the error message - "OSS DB Tools service exited unexpected. Please restart Azure Data Studio" I am attaching the error screenshot too.

Could you please let me know the complete steps to solve the issue to connect with the PostgreSQL DB.

**Comment by dpfrakes** [comment]
I was having the same issue, did you try this workaround?:
https://github.com/microsoft/pgtoolsservice/issues/239#issuecomment-653665504

**Comment by nasc17** [comment]
Please update to the latest stable release of PostgreSQL extension v0.4.2. Reopen if issue persists, thank you.
