### ISSUE TITLE
Error OSS DB Tools Service component exited unexpectedly on Win 10

### ISSUE THREAD

**Issue by digimen-ch** [microsoft/azuredatastudio-postgresql#320]
Windows did some updates today. After a reboot I start Data Studio I cannot connect to Postgres and got this error message.

Here the updates Windows installed today: 
![image](https://user-images.githubusercontent.com/30627772/168310373-d335a469-c92e-435f-82b6-5be6ef47068f.png)

Anyone a solution for this?

**Comment by nasc17** [comment]
Update to latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
