### ISSUE TITLE
When trying "Script as Create" it won't work for PostgreSQL

### ISSUE THREAD

**Issue by luqq** [microsoft/azuredatastudio-postgresql#321]
Right Clicking any table will show this log on output:
```
[Error - 02:17:43] Request scripting/script failed.
  Message: column rel.relhasoids does not exist
LINE 8:   pg_get_userbyid(rel.relowner) AS relowner, rel.relhasoids,
                                                     ^

  Code: 0 
[object Object]
```

It works just fine in SQL Server.

ADS version: 1.36.2
PostgreSQL plugin version: v0.2.7
PostgreSQL server version: postgres (PostgreSQL) 14.3 (Ubuntu 14.3-1.pgdg22.04+1)

It won't even work with _EFMigrationsHistory table
![image](https://user-images.githubusercontent.com/1941430/170152885-76ac3220-cc0f-4090-8492-b3b9c4fc7889.png)

Hope this helps!
Thank you

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/225. Closing the issue
