### ISSUE TITLE
Error Trying to Load PostgreSQL extension on Azure Data Studio

### ISSUE THREAD

**Issue by jaji813** [microsoft/azuredatastudio-postgresql#325]
Hello,

While trying to download the PostgreSQL extension, got the below errors:

1st Error: Failed to install 'microsoft.azuredatastudio-postgresql'. Download manually.
2nd Error: "Unable to install version '0.2.7' of extension 'microsoft.azuredatastudio-postgresql' as it is not compatible with Azure Data Studio '1.12.2'. (also attached error).

Any suggestions?  Thank you kindly.

![Error_AzureDataStudio_PostgreSQL_20220713](https://user-images.githubusercontent.com/56519773/178649342-88db1543-2a00-45f8-b983-415a2394478f.jpg)

**Comment by nasc17** [comment]
Update to latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
