### ISSUE TITLE
Cannot edit data row

### ISSUE THREAD

**Issue by kakins** [microsoft/azuredatastudio-postgresql#326]
I'm getting this error whenever trying to edit any field in my table using the data editor.  I cannot add new rows or edit existing ones.
```
[Error - 8:06:30 PM] Request edit/createRow failed.
  Message: Unknown string format: CURRENT_TIMESTAMP
  Code: 0 
```

I also occasionally get this error
```
[Error - 8:09:23 PM] Request edit/createRow failed.
  Message: Unhandled exception while handling request method edit/createRow: "'Edit session not found'"
  Code: -32603 
```

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
