### ISSUE TITLE
Script As Create Fails 

### ISSUE THREAD

**Issue by alnoel** [microsoft/azuredatastudio-postgresql#330]
Issue Type: <b>Bug</b>

Attempts to execute "Script as Create" fail. 

DBMS:  PostgreSQL 14
ADS:  

Version: 1.39.0 (user setup)
Commit: 9fdb2161d49b4d4ab6798809faa042a898ca2eae
Date: 2022-08-20T01:46:47.606Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

OS: 

Edition	Windows 10 Pro
Version	21H2
Installed on	‎6/‎18/‎2020
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

Extension:

PostgreSQL v0.2.7

Error Message (there some column no longer available in the DBMS to be queried?) 

"It seems the debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
[Error - 8:35:20 AM] Request scripting/script failed.
  Message: column rel.relhasoids does not exist
LINE 8:   pg_get_userbyid(rel.relowner) AS relowner, rel.relhasoids, "
                                                     ^

Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.39.0 (9fdb2161d49b4d4ab6798809faa042a898ca2eae, 2022-08-20T01:46:47.606Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100T CPU @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (22.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/225. Closing the issue
