### ISSUE TITLE
Cannot open database list (Error: Failed to expand node)

### ISSUE THREAD

**Issue by bwong365** [microsoft/azuredatastudio-postgresql#333]
Using PostgreSQL 15.0
MacOS Monterey 12.6
Azure Data Studio 1.39.1

Unable to open the list of databases (silently fails on left-click).
Error pops up when right clicking the database list and hitting Refresh.

**Comment by ScriptBytes** [comment]
I am also having this issue.
Postgres 15
Azure Data Studio v1.40.0
PostgreSQL Extension v0.2.7

**Comment by wehnertb** [comment]
This fixed the error for me.  https://github.com/microsoft/azuredatastudio-postgresql/issues/334

**Comment by ScaryDBA** [comment]
I'm hitting this error. Also, the System Databases folder hits the same issue.
PostgreSQL 15
ADS 1.40.1
PostgreSQL Extension 0.2.7

**Comment by NarishSingh** [comment]
Facing the same issue. I can connect and run queries but this error occurs for Databases and System Databases

PostgreSQL 15
ADS 1.40.1
PostgreSQL Extension 0.2.7
Windows 10

The fix cited earlier on #334 did not work for me

**Comment by jammerware** [comment]
Occurs when I try to expand databases on a local server. The fix from #334 got me part of the way there, but, possibly due to server configuration (I'm new to Postgres), I had to put double quotes around column aliases in `nodes.sql`. Final code here:

```sql
{#
 # pgAdmin 4 - PostgreSQL Tools
 #
 # Copyright (C) 2013 - 2017, The pgAdmin Development Team
 # This software is released under the PostgreSQL Licence
 #}
SELECT
    db.oid as "oid", 
    db.datname AS "name", 
    ta.spcname as spcname, 
    db.datallowconn,
    0 as datlastsysoid,
    has_database_privilege(db.oid, 'CREATE') as cancreate, 
    datdba as owner, 
    db.datistemplate , 
    has_database_privilege(db.datname, 'connect') as canconnect,
    datistemplate as is_system
FROM
    pg_database db
LEFT OUTER JOIN pg_tablespace ta ON db.dattablespace = ta.oid
{% if did %}
WHERE db.oid = {{ did|qtLiteral }}::OID
{% elif last_system_oid %}
WHERE db.oid > {{ last_system_oid }}::OID
{% endif %}

ORDER BY datname;
```

**Comment by solmazeradat** [comment]
Having the same issue with the same setup as @NarishSingh. Any Ideas on how to fix this? thanks

**Comment by jammerware** [comment]
@solmazeradat Did you see my comment above? I had to quote the column aliases, which I think is some config thing specific to certain installations of Postgres. Give it a try, maybe?

**Comment by LanceTrahan** [comment]
For anyone that may not be aware, if you're on a Mac, the path to the nodes.sql that @jammerware supplied a correction to can be found at:
`/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.7/out/ossdbtoolsservice/OSX/v1.5.0/pgsqltoolsservice/lib/pgsmo/objects/database/templates/+default/nodes.sql`

**Comment by RodrigoNunes2004** [comment]
Great, somehow I figure out the issue Thanks!

**Comment by potatoqualitee** [comment]
It's also happening when I try to expand Indexes

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/357, closing the issue
