### ISSUE TITLE
Error when disconnecting from Postgres 15.0 connection

### ISSUE THREAD

**Issue by bwong365** [microsoft/azuredatastudio-postgresql#334]
From Azure Data Studio: 
```SQL
Failed to close OE session: column db.datlastsysoid does not exist.
```

On the Postgres side:
```SQL
2022-10-19 19:03:14.467 UTC [189] ERROR:  column db.datlastsysoid does not exist at character 106
2022-10-19 19:03:14.467 UTC [189] STATEMENT:  
SELECT
    db.oid as oid, 
    db.datname as name, 
    ta.spcname as spcname, 
    db.datallowconn,
    db.datlastsysoid,
    has_database_privilege(db.oid, 'CREATE') as cancreate, 
    datdba as owner, 
    db.datistemplate , 
    has_database_privilege(db.datname, 'connect') as canconnect,
    datistemplate as is_system

FROM
    pg_database db
    LEFT OUTER JOIN pg_tablespace ta ON db.dattablespace = ta.oid
 ORDER BY datname;
```

**Comment by jonashilmersson** [comment]
+1

**Comment by dtwilliams10** [comment]
+1

**Comment by wehnertb** [comment]
+1 - Thank you!

**Comment by jammerware** [comment]
> I fixed it locally. go to %USERPROFILE%.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.2.7 find nodes.sql file in the sub directory out\ossdbtoolsservice\Windows\v1.5.0\pgsqltoolsservice\lib\pgsmo\objects\database\templates+default\
> 
> change db.datlastsysoid, to 0 as datlastsysoid, in the sql text. save and reopen the azure data studio

This was really helpful, thank you! For anyone for whom this doesn't fix it, note that you may have to do a little more depending on... factors I don't really understand as a Postgres newbie 🤣 See my [comment here](https://github.com/microsoft/azuredatastudio-postgresql/issues/333#issuecomment-1348835770).

**Comment by aaronschendel** [comment]
> 0 as datlastsysoid,

This fixed my issue today - thank you!

**Comment by sanyog2491** [comment]
> I fixed it locally. go to %USERPROFILE%.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.2.7 find nodes.sql file in the sub directory out\ossdbtoolsservice\Windows\v1.5.0\pgsqltoolsservice\lib\pgsmo\objects\database\templates+default\
> 
> change db.datlastsysoid, to 0 as datlastsysoid, in the sql text. save and reopen the azure data studio

how to open this m really not getting how to fix using this solution

**Comment by RachelAmbler** [comment]
For MacOS this can be found at 

`~/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.7/out/ossdbtoolsservice/OSX/v1.5.0/pgsqltoolsservice/lib/pgsmo/objects/database/templates/+default/nodes.sql`

**Comment by lucadistefano** [comment]
@RachelAmbler @Aidan-Chang thanks it fixed the problem for me too

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/357. Closing the issue
