### ISSUE TITLE
The debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py

### ISSUE THREAD

**Issue by qwertybba** [microsoft/azuredatastudio-postgresql#336]
My purpose is to manage PostgreSQL databases in Azure Data Studio, so I added a new connection successfully, but when I click on the arrow in the Serves section
![Postgres1](https://user-images.githubusercontent.com/20028775/202987751-715d9fdd-dd03-4c8a-955f-1c9e04545a4d.jpg)

 I got this error message:
**It seems the debugger cannot resolve C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\ntpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193**

If I try to open the Databases or System Databases folders, I got this error message:
**Error: Failed to expand node**

On Manage Section when I right click on any table and choose
Edit Data I got this error message
**Failed to generate script for Edit Data editor.** 
With this output
[Error - 8:24:06 AM] Request scripting/script failed.
  Message: Object of type NoneType does not support script operation ScriptOperation.SELECT
  Code: 0

And when I choose Select Top 1000 I got this error message 
**Failed to generate select script for the selected object.**
With this output
[Error - 8:25:57 AM] Request scripting/script failed.
  Message: Object of type NoneType does not support script operation ScriptOperation.SELECT
  Code: 0 

I am able to perform CRUD operations without any issues in a new query.

Windows 11 22H2
Azure Data Studi 1.40.0
PostgreSQL extension 0.2.7

**Comment by christopherowenowens** [comment]
Thank you for reporting this. I am also having a similar issue.

Azure Data Studio 1.39.1 on Linux (Kubuntu).
Installed Postgresql extension from Microsoft.
Get the "cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py" error, even after restarting program.
Can't create new connection to postgres server; after entering URL / user / password and 'Connect', it never resolves after 2 minutes; have to click cancel.

**Comment by qwertybba** [comment]
Any news.

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
