### ISSUE TITLE
Unable to connect to Azure PostgreSQL via Azure Data Studio.

### ISSUE THREAD

**Issue by xyz-mtl** [microsoft/azuredatastudio-postgresql#344]
I can't connect to Postgres from the latest version of Azure Studio. Render[1] error

**Comment by NokoAnubis** [comment]
I just can't connect at all, it hangs. I used another tool and I connected successfully.

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/356. Closing this issue
