### ISSUE TITLE
Failed to start Pgsql tools service (Macbook M1)

### ISSUE THREAD

**Issue by cesar-kbfmf** [microsoft/azuredatastudio-postgresql#345]
PostgreSQL v0.2.7
Azure Database Studio v1.40.2

Macbook Air (M1,2020)
macOS Monterey (v12.6)

Trying to download the extension from ADS or manually vsix still wont help.
Is it bug? can you fix this? thank you

**Comment by lukasz-cpu** [comment]
Failed to start Pgsql tools service

I have the same issue

**Comment by jakobwegener** [comment]
I have the same issue. Anyone found fixes or workarounds?

Macbook air M2 2022
macOS: Ventura 13.1
Azure Database Studio v1.40.2
OS: Darwin arm64 22.2.0

**Comment by DataKnox** [comment]
Same issue

Macbook Pro M2 
Ventura 13.0
Azure Data Studio v1.40.2
extension v0.2.7

**Comment by rafaelporto** [comment]
Same here:
Macbook Pro M1
Ventura 13.1
Azure Data Studio v1.41.0
extension v0.2.7

**Comment by cesar-kbfmf** [comment]
I don't find any solution for this issue or the dev team cares about this issue.

This is just a hunch, maybe the extension cant run on the M1 machine. Even I run the intel version on M1 machine and still got the same error. Anyone know how to run the extension on rosseta?

**Comment by tony-cocco** [comment]
Same issue for me:

Apple M1 Pro
Ventura 13.1
Azure Data Studio 1.41.0
Extension 0.27.0

Coworker has no issues on his Windows laptop.

**Comment by davidscheidtbitstop** [comment]
Found a (not satisfactory) work around... Download the Universal version of Azure Data Studio.  Then, do 'Get Info' on the Azure Data Studio Icon, and select 'Open with Rosetta'.  This gets the Postgres extension to work.  Unfortunately, is also slows down Azure Data Studio

**Comment by lukasz-cpu** [comment]
are there any updates?

**Comment by davidscheidtbitstop** [comment]
I wish I had some updates, I'm in the same boat.  I just posted a work
around that I found.

**Comment by joeballard** [comment]
Me too!

MacBook Pro M2
Ventura 13.3.1
Azure Data Studio 1.43.0
Extension 0.2.7

FWIW: My _workarounds_ are [Postico](https://postgresapp.com) & [Navicat](https://www.navicat.com/en/products/navicat-for-postgresql)

**Comment by andershermansen** [comment]
Try the 0.3.0 pre release, it worked fine for me.

**Comment by Baune8D** [comment]
0.3.0 works great here also! 👍

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/356. Closing this issue
