### ISSUE TITLE
Not able to connect to PostGres error "Failed to start Pgsql tools service" MAC OS Monterey 12.6.1 (M1 Chip)

### ISSUE THREAD

**Issue by jonathanascencio93** [microsoft/azuredatastudio-postgresql#346]
Not able to connect to PostGres error "Failed to start Pgsql tools service" MAC OS Monterey 12.6.1. I have tried to uninstall plugin and uninstall app but keep getting this error

**Comment by awaitJosh** [comment]
> Not able to connect to PostGres error "Failed to start Pgsql tools service" MAC OS Monterey 12.6.1. I have tried to uninstall plugin and uninstall app but keep getting this error

Same with Ventura 13.1

**Comment by DaeunYim** [comment]
Tracking from https://github.com/microsoft/azuredatastudio-postgresql/issues/356, closing the issue
