### ISSUE TITLE
Starting client failed ossdbtoolsservice_main.exe failed.

### ISSUE THREAD

**Issue by sridharanprasanna** [microsoft/azuredatastudio-postgresql#350]
[Error - 5:17:40 pm] Starting client failed
Launching server using command c:\Users\prasas\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.2.7\out\ossdbtoolsservice\Windows\v1.5.0\pgsqltoolsservice\ossdbtoolsservice_main.exe failed.

Couldn't start client ossdbToolsService

OS: Windows11
Client: V1.41.2 (user setup) & (system setup)

Steps tried:
- Uninstall all and install the extension again
- Restart the machine
- Reinstall the ADS

![image](https://user-images.githubusercontent.com/13363348/219020256-c9d2bb43-cf8d-4044-b0a8-b363b2227b13.png)

None of the above worked.

**Comment by IdresAhmed** [comment]
I am facing the same issue. My installation details are as follows:
Version: 1.41.2 (system setup)
Commit: 0f0960d0e774e1ce903b79378addff96117c27a6
Date: 2023-02-08T20:16:49.071Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by IdresAhmed** [comment]
> I am facing the same issue. My installation details are as follows: Version: 1.41.2 (system setup) Commit: 0f0960d0e774e1ce903b79378addff96117c27a6 Date: 2023-02-08T20:16:49.071Z VS Code: 1.67.0 Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22621

This is working for me now. Uninstall and re-install was not working as ADS leaves behind cache. Deleting '/users/<username>/.azuredatastudio' and '/users/<username>/AppData/Roaming/azuredatastudio' helped.

**Comment by sagangwar** [comment]
In Linux version 1.40.2 and 1.41.2 I am getting this error mentioned in the screenshot below:
![image](https://user-images.githubusercontent.com/96845250/219966181-8473343e-e3d3-44ae-948c-1f3e64136660.png)

**Comment by IdresAhmed** [comment]
> In Linux version 1.40.2 and 1.41.2 I am getting this error mentioned in the screenshot below: ![image](https://user-images.githubusercontent.com/96845250/219966181-8473343e-e3d3-44ae-948c-1f3e64136660.png)

I was able to get past this. This is largely happening as it is not able to find `libffi.so.6`
First, run `ls -la /usr/lib/x86_64-linux-gnu/libffi*` to see the versions installed for libffi. If you have 7 installed, then link 6 and 7 using the command `sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6`.

If you have only version 8 etc you can try direclty installing V6 using ```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```
