### ISSUE TITLE
Failed to start Pgsql tools service

### ISSUE THREAD

**Issue by jmkubecka** [microsoft/azuredatastudio-postgresql#351]
Upon installing the PostgreSQL extensions for Azure Data Studio, I get a "Failed to start Pgsql tool service" message.  I am running Azure Data Studio on a Mac with a M2.  

I've tried...

Uninstall/Install
Installing Azure Data Studio - Apple silicon version
Installing Azure Data Studio - Universal version

**Comment by tkfalarz** [comment]
Same story here...

**Comment by cocoataster** [comment]
After an hour of research, I've managed to get this working by enabling Rosetta for this App.

Otherwise, will not work at all :(

**Comment by ipalo** [comment]
Any news on fixing this issue for ARM?

**Comment by DaeunYim** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio-postgresql/issues/356. Closing the issue
