### ISSUE TITLE
Error: Failed to expand node

### ISSUE THREAD

**Issue by KeithCouch** [microsoft/azuredatastudio-postgresql#353]
Within Azure Data Studio, using PostgreSQL extension for Azure Data Studio v0.2.7, I am unable to use the dropdown to open databases.  I get a pop up "Error: Failed to expand node"
I have uninstalled and reinstalled the extension several times.

**Comment by KeithCouch** [comment]
Now the server tree will not expand at all.

**Comment by PureKrome** [comment]
Same here @KeithCouch - extension totally unusable. 😢

**Comment by beautifulcoder** [comment]
Issue #333 has a work around

**Comment by DaeunYim** [comment]
Being tracked in https://github.com/microsoft/azuredatastudio-postgresql/issues/357. Closing the issue
