### ISSUE TITLE
Failed to start Pgsql tools service on MacOS

### ISSUE THREAD

**Issue by Joey-JJ** [microsoft/azuredatastudio-postgresql#356]
Steps to Reproduce:

1. Install PostgreSQL extension (v0.1.0) through the Extension Manager (following instructions from https://docs.microsoft.com/en-us/sql/azure-data-studio/postgres-extension?view=sql-server-2017)
2. Restart Azure Data Studio
3. Popup displays in bottom right corner with the message "Failed to start Pgsql tools service". Expanding the dialog (arrow icon) gives "Source: PostgreSQL (Extension)".

**Comment by akonyer** [comment]
It does not work on the ARM version of Azure Data Studio.

This project seems to be abandoned as far as I can tell.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
