### ISSUE TITLE
cannot edit data

### ISSUE THREAD

**Issue by ositaunus** [microsoft/azuredatastudio-postgresql#374]
Issue Type: <b>Bug</b>

if i execute a query with UPDATE it works, if i do it through the Edit Data option i get

[Error - 1:46:51 PM] Request edit/commit failed.
  Message: Table report does not have a single column that can be trusted for uniqueness
  Code: 0 

Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:08:07.209Z)
OS version: Linux x64 5.15.0-71-generic
Restricted Mode: No
Preview Features: Enabled

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
