### ISSUE TITLE
Save as Excel  (PostgreSQL Extension) 

### ISSUE THREAD

**Issue by RodrigoBurgosMella** [microsoft/azuredatastudio-postgresql#375]
when trying to export to excel, the process waits indicating "Saving File" and never ends

![image](https://user-images.githubusercontent.com/12177217/235952932-14589521-5338-4a74-a568-06ed7c36b038.png)

**Comment by gcapnias** [comment]
I run on the same problem when I tried to export data that included binary columns (postgis geometries).

Lately, I found out the problem exists even if you have nonbinary columns, just a lot of lines...


George J.

**Comment by gcapnias** [comment]
Same as issue #314

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
