### ISSUE TITLE
Error: Failed to expand node

### ISSUE THREAD

**Issue by daryoosh-hoora** [microsoft/azuredatastudio-postgresql#387]
Issue Type: <b>Bug</b>

Hi there,
Connecting to Postgres server is successful, but by clicking on `Databases` to expand database folder, the Error: Failed to expand node will be raised.

Extension version: 0.2.7
Azure Data Studio version: azuredatastudio 1.43.0

![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/106872770/25674d1a-163c-47d0-8d43-94e81a7d97e6)

**Comment by nasc17** [comment]
Hi @daryoosh-hoora what is the version of your Postgres is server?

**Comment by daryoosh-hoora** [comment]
Hi,
I'm using PostgreSQL 15.2 installed on Ubuntu server.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.

**Comment by daryoosh-hoora** [comment]
Yes it's been fixed, Thanks.

![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/106872770/52fad45e-3bdf-40c5-9843-4c3867bb9f1c)
