### ISSUE TITLE
Why is the 0.3.1-win-x64 download so much larger than other downloads?

### ISSUE THREAD

**Issue by schallm** [microsoft/azuredatastudio-postgresql#391]
All downloads except the 0.3.1-win-x64 version are ~1.5MB in size.  Why is the 0.3.1-win-x64 version 175MB in size?

https://github.com/microsoft/azuredatastudio-postgresql/releases

**Comment by DaeunYim** [comment]
We are having issue with offline packaging vsix files for OSX. The vsix files for osx platform will be replaced by offline packages once the issue is resolved.
