### ISSUE TITLE
Failed to start PGSQL tools service on Windows 10 Enterprise

### ISSUE THREAD

**Issue by dtieppo** [microsoft/azuredatastudio-postgresql#396]
Type: <b>Bug</b>

Failed to start PGSQL tools service is the message that appears when I open Azure Data Studio after latest update.

Extension version: 0.3.1
Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (23.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2. We would appreciate your verification if this issue is still present.
