### ISSUE TITLE
Azure Cosmos DB for PostgreSQL instances do not show in Azure resources list.

### ISSUE THREAD

**Issue by GaryHopeMS** [microsoft/azuredatastudio-postgresql#398]
Azure Cosmos DB for PostgreSQL cluster instances in my subscription are not shown in the server list.

Add section named "Azure Cosmos DB for PostgreSQL" 
Add all Azure Cosmos DB for PostgreSQL clusters as children to list.
Expose all object functionality as per PostgreSQL server objects.

**Comment by nasc17** [comment]
Fixed by Azure Data Studio: https://github.com/microsoft/azuredatastudio/pull/23300
Next Azure Data Studio update will be released July 2023

**Comment by GaryHopeMS** [comment]
https://github.com/microsoft/azuredatastudio/pull/23300 does not address the Azure Cosmos DB for PostgreSQL resources.

**Comment by nasc17** [comment]
Addressed by ADS: https://github.com/microsoft/azuredatastudio/issues/23459

**Comment by nasc17** [comment]
Azure Data Studio v1.45.0 has been released
