### ISSUE TITLE
When I try to install 0.3.1 from local file I see `Version specified in engines.vscode (*) is not specific enough`

### ISSUE THREAD

**Issue by xperiandri** [microsoft/azuredatastudio-postgresql#405]
`Version specified in engines.vscode (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.`

![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/2365592/ba8cfe46-416d-4f68-8d40-1eabb28527ee)

**Comment by xperiandri** [comment]
Windows 11

**Comment by nasc17** [comment]
Can you also please also share the About information for your Azure Data Studio: press Help, click About, and copy contents. Thank you

**Comment by xperiandri** [comment]
I did that in VS Code, not Data Studio
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/2365592/c2e4088d-570f-40c9-892f-6ec4b998eb91)
Version: 1.79.0 (system setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by nasc17** [comment]
This extension is meant for use in Azure Data Studio, ADS. Please [download and install ADS](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall) and you can get the PG extension from their marketplace. 
Please reopen issue if you still have troubles install in ADS.
