### ISSUE TITLE
Extension issue - Failed to start PGSQL tools service on Ubuntu

### ISSUE THREAD

**Issue by bmuriithi1** [microsoft/azuredatastudio-postgresql#407]
- Issue Type: `Bug`
- Extension Name: `azuredatastudio-postgresql`
- Extension Version: `0.3.1`
- OS Version: `Linux x64 5.19.0-35-generic`
- VS Code version: `1.44.1`

**Problem**: I try to connect to postgres DBs in my Azure subscriptions using Azure Data Studio. My OS is Ubuntu 22.04. It looks like it's stuck trying to connect for a long period of time and I have to manually cancel the connection attempt. I think this might be linked to the PostgreSQL extension not working for me, see below. 

![endless_connection_ads](https://github.com/microsoft/azuredatastudio-postgresql/assets/99765572/4a59419b-6e07-4b6f-903f-d085ea08520d)

**Debugging efforts:** 
When launching the ADS app on my ubuntu OS, I'm getting the error 'Failed to start PGSQL tools service'. I suspect this is a contributing factor, if not the main cause of the problem. 
![Failing_Postgres_extension](https://github.com/microsoft/azuredatastudio-postgresql/assets/99765572/3171f5e5-cd2d-44bd-8ac1-87a76aacf56c)

When I change the log level to 'Debug' and reload ADS, I get the following output in the terminal. Looks like a TypeError is occuring because it's trying to read something that's undefined. 

![Output_log](https://github.com/microsoft/azuredatastudio-postgresql/assets/99765572/38cc3de4-ec0a-4ee3-a8d5-cdfaed833313)

When I toggle developer settings in ADS after activating debug mode, I get the following output: 

![dev_console_output](https://github.com/microsoft/azuredatastudio-postgresql/assets/99765572/eee0b845-a9b1-4885-94c7-e4652f326010)

Things I've tried: 
- Uninstalling and reinstalling the PostgreSQL extension 
- Uninstalling and reinstalling Azure Data Studio on my Ubuntu OS 
- Double-checking that libpq5 and openssl are installed in my OS (PostgreSQL extension dependencies) 
- Installing the extension using the 0.3.1 vsix file from https://github.com/Microsoft/azuredatastudio-postgresql/releases/ but this didn't work.

I found similar issues (https://github.com/microsoft/azuredatastudio-postgresql/issues/108, https://github.com/microsoft/azuredatastudio-postgresql/issues/122) but none of the solutions in there worked for me.

Any thoughts/suggestions?

**Comment by karabaja4** [comment]
Check #392, #395.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by bmuriithi1** [comment]
Can confirm v0.4.0 works fine for me now, thanks for the update!
