### ISSUE TITLE
Error: The session ID returned by provider "PGSQL" for connection xxx is invalid.

### ISSUE THREAD

**Issue by dtieppo** [microsoft/azuredatastudio-postgresql#423]
It is the second time that I update the app and have posterior issues with the connections using PostgresSQL. Tried to install extension from vsix, got connected although getting the following error: The session ID returned by provider "PGSQL" for connection xx is invalid.
Already reviewed connections and re-installed ADS. 
What else can be done?
Thanks!

**Comment by tlunsfordCXP** [comment]
Same problem here. Would love to go back to a previous version, but only the current version is available in the extension.

**Comment by DaeunYim** [comment]
Can you provide the desktop platform and PG version please?

You can download the previous versions [here](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.3.1).

**Comment by dtieppo** [comment]
Windows 10 64bit, PG 0.4.2

**Comment by dtieppo** [comment]
Version 0.3.1 worked. Let´s see how much it lasts.

**Comment by DaeunYim** [comment]
> Same problem here. Would love to go back to a previous version, but only the current version is available in the extension.

We will work on the fix. Did restating ADS not fix the issue at all?

**Comment by DaeunYim** [comment]
Closing after stable release

**Comment by nasc17** [comment]
Hello, issue has been addressed in our unstable release of PostgreSQL extension v0.4.3-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by dtieppo** [comment]
Once updated both ADS and extension, failed, same message. I would need to
install an older version like I did before but this new extension installed
by itself.

**Comment by nasc17** [comment]
@dtieppo Could you please try the following steps?

Navigate to C:\Users<user_name>.azuredatastudio\extensions and clear out any existing PostgreSQL extensions. (Don't worry about losing your connection info, they will appear once you re-install the extension)

Open your file explorer, go to the %temp% location, and remove any folders named _MEI<6digit number> if they exist.

Once you've completed these steps, please try downloading and installing the new version of the PostgreSQL extension again.

Please let us know if this resolves the issue or if you need further assistance.

**Comment by dtieppo** [comment]
Resolved! Thank you very much!
