### ISSUE TITLE
Dashboard: Server level dashboard shows 'unable to load dashboard properties'

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#43]
SQL Ops version: 12/21/2017- daily build
Postgres Version: 9.5

Repro Step:
(1) Open SQL Ops and connect to a database via the connection dialog.
(2) Once connected, the dashboard will show up, then click the server level 'localhost':
![image](https://user-images.githubusercontent.com/30940057/35360293-19d0348a-0112-11e8-8be7-28e77db01906.png)

Expected: The server level dashboard should look like the MSSQL and have all the components displayed.
Fact: The server level dashboard shows 'Unable to load dashboard properties'
![image](https://user-images.githubusercontent.com/30940057/35360011-1479ba16-0111-11e8-9068-bfa15f708822.png)

**Comment by keithnicholson** [comment]
This quit working for me somewhere in the last couple of months since I used it.  I need the properties so that I can do a backup again.
