### ISSUE TITLE
Transactions can't be managed explicitly

### ISSUE THREAD

**Issue by awhalbert** [microsoft/azuredatastudio-postgresql#433]
**Description**
BEGIN;
INSERT INTO foo
VALUES ('foo');
ROLLBACK;

The above commits, rather than rolls back. The value exists in the table.

**Repro**
Try to use explicit transactions and control whether they commit or roll back.

**OS**
Windows 11 Enterprise Version 10.0.22621 Build 22621

**Versions**
- ADS
  - ![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/7232559/5be0e648-51b5-4be1-a148-0990f74e6fc0)
- ADS PostgresSQL etension version
  - v0.4.2
- PostgreSQL version
  - PostgreSQL 12.7, compiled by Visual C++ build 1914, 64-bit

**Comment by mistermiracl** [comment]
I can confirm this, when I was on 0.2.7 I could use explicit transaction without any issues, now that I'm on 0.4.2 BEGIN/BEGIN TRANSACTION are simply ignored

**Comment by S4NT14G0** [comment]
Same issue here.  Basically rendering this unusable for me and my team.

**Comment by DaeunYim** [comment]
We will work on the fix. Meanwhile, you can download the previous version here https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.3.1

**Comment by nasc17** [comment]
Hello, issue has been addressed in our unstable release of PostgreSQL extension v0.4.3-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by awhalbert** [comment]
Hi, I installed 0.4.3 (Win64) but I get this when I try to initiate any database connection:
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/7232559/7cee90ea-5aec-4742-9d55-98f71fbf15c0)

**Comment by DaeunYim** [comment]
@awhalbert can you check the latest stable release 0.5.0? Otherwise, we will need more information on your connection params.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.5.0. Please reopen if issue is still present, thank you.
