### ISSUE TITLE
JSON viewer taking too long to open

### ISSUE THREAD

**Issue by mistermiracl** [microsoft/azuredatastudio-postgresql#436]
**Describe the bug**
Azure Data Studio JSON viewer is taking too long to open when clicking on fields containing JSON data, about 20-30 seconds

**To Reproduce**
1. Query a table with JSON data
2. Click on the field containing JSON data
3. Experience the delay

**Expected behavior**
The JSON viewer should open almost instantly, Just like with previous postgres extensions versions. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**ADS (please complete the following information):**
 - ADS Version: 1.44.1
- ADS PostgresSQL etension version: 0.4.2
- PostgreSQL version: 14.7

**Additional context**
This issue did not exist in previous version name extension 0.2.7, after upgrading this started happening. Also, for SQLServer databases with JSON fields on the same Azure Studio version there's not delay when opening the JSON viewer.

**Comment by nasc17** [comment]
@mistermiracl could you please update to latest stable release of PostgreSQL extension v0.5.0 and Azure Data Studio v1.45.1. We would appreciate your verification if this issue is still present, thank you.

**Comment by mistermiracl** [comment]
all good now, thanks!
