### ISSUE TITLE
Unhandled exception while executing query: Object of type UUID is not JSON serializable

### ISSUE THREAD

**Issue by komuch86** [microsoft/azuredatastudio-postgresql#446]
**Describe the bug**
Problem is with column that has table uuid data type

**To Reproduce**
Steps to reproduce the behavior in the screenshot above:

**Expected behavior**
No error

![obraz](https://github.com/microsoft/azuredatastudio-postgresql/assets/84025614/2d050c3b-2c9c-4048-9d92-82c917292b15)

 - OS: Windows11

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.5.0. Please reopen if issue is still present, thank you.
