### ISSUE TITLE
Scripting fails after system wakesup for postgres objects

### ISSUE THREAD

**Issue by sahalMoidu** [microsoft/azuredatastudio-postgresql#454]
**Describe the bug**
After the computer sleeps and wakes up, the connection to the postgres server seems to invalid. When trying to script select or create using the context menu scripting failed error occurs

> Object of type NoneType does not support script operation ScriptOperation.SELECT

**To Reproduce**
1. Connect to postgres server
2. Let  your computer sleep for  a while, possibly overnight
3. Wake up and try to do any operation on the context menu of the table

**Expected behavior**
If the connection is timed out or lost, it should automatically reconnect and be able to resume operation

**Screenshots**
<img width="784" alt="image" src="https://github.com/microsoft/azuredatastudio-postgresql/assets/6101879/b749f6a5-8fd7-4175-89dd-ef80204b7256">

**Desktop (please complete the following information):**
 - OS: Mac

**ADS (please complete the following information):**
 - ADS Version 
 - 
Version: 1.45.0
Commit: 8eff468100f02157f2219335f7a566d14451ca49
Date: 2023-07-24T18:20:58.743Z (1 wk ago)
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.3.0
- ADS PostgresSQL etension version
V.0.5.0

**Additional context**
Earlier before updating to current version session id error used to appear as  described in #423

**Comment by sahalMoidu** [comment]
@nasc17 possibly a related error occurs when trying to expanding node
Failed to expand node: consuming input failed: Operation timed out
SSL SYSCALL error: Operation timed out

<img width="702" alt="image" src="https://github.com/microsoft/azuredatastudio-postgresql/assets/6101879/64b62681-d898-4acd-ad54-8f9a8728aaa8">

**Comment by nasc17** [comment]
> @nasc17 possibly a related error occurs when trying to expanding node Failed to expand node: consuming input failed: Operation timed out SSL SYSCALL error: Operation timed out
> 
> <img alt="image" width="702" src="https://user-images.githubusercontent.com/6101879/264062525-64b62681-d898-4acd-ad54-8f9a8728aaa8.png">

Are you still using the v0.5.0 extension seeing this error or insiders?

**Comment by sahalMoidu** [comment]
@nasc17 another one similar is when trying to run a query on  query editor

None
Error while rolling back open transaction due to previous failure: None

<img width="639" alt="image" src="https://github.com/microsoft/azuredatastudio-postgresql/assets/6101879/fcde7edb-694c-4ad8-99ee-37f033778148">

**Comment by nasc17** [comment]
Thank you for the added information. We are working on getting out a release to address the issue. Will keep you updated on how to verify fixes shortly.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/a4a11e12-3eb1-4735-a9bf-43a1c685af7d)
