### ISSUE TITLE
PL/pgSQL scripts RAISE command and Messages

### ISSUE THREAD

**Issue by gcapnias** [microsoft/azuredatastudio-postgresql#455]
I use the PostgreSQL extension for Azure Data Studio to run PL/pgSQL scripts. I use RAISE commands to provide feedback while running scripts.

In the previous versions, each RAISE command had a distinct color and a line in the messages pane, depending on the level (INFO, EXCEPTION, etc.). In the latest versions, I get all the RAISE messages after the script finishes, and they are all concatenated in one line, which makes them impossible to read.

Is it possible to change it back to the original behavior? Or at least have each message on a separate line in the results?

Thanks,
George J.

**Comment by nasc17** [comment]
@gcapnias could you please inform us of the version of Postgresql extension and Azure Data Studio you were using previously and what you updated to when you change in behavior.

**Comment by gcapnias** [comment]
Version v0.5.0, the latest...


Regards,
George J.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by gcapnias** [comment]
Hi,

Yes, I can verify that `v0.5.1-insiders` has returned each message in a separate line; you can read them easily!


Thanks,
George J.

**Comment by nasc17** [comment]
Please be on the lookout for when we publish the next stable release of the extension. Thank you!
