### ISSUE TITLE
Problem with INTERVAL output

### ISSUE THREAD

**Issue by LSIND** [microsoft/azuredatastudio-postgresql#459]
**Describe the bug**
Using datatype INTERVAL produce incorrect results in the Results grid.

**To Reproduce**

1. Run SELECT-statements below which produce INTERVAL datatype as return value:
```sql
SELECT '1 year 2 months 20 days 1 hour'::INTERVAL AS i;

SELECT age('20100101'::date, '19940215'::date) AS age_func;

SELECT date_trunc('months', '1 year 2 months 20 days 15 minutes 55 seconds'::interval) as date_trunc_func;

SELECT 5 * '2 years 3 months 5 days'::interval as mult;
```
2. In the Results window there are only days though it is obvious there should be also years and months in all queries: 
```sql
        i
-------------------
20 days, 1:00:00 

    age_func
-------------------
14 days, 0:00:00

  date_trunc_func
-------------------
60 days, 0:00:00

      mult
-------------------
25 days, 0:00:00
```

**Expected behavior**
It seems that ADS or extension cuts everything that stands before the days.

As for `psql (13.8)`, it produces correct results:
```sql
=# SELECT '1 year 2 months 20 days 1 hour'::INTERVAL AS i;
----------------------------------------------
1 year 2 mons 20 days 01:00:00

=# SELECT age('20100101'::date, '19940215'::date) AS age_func;
----------------------------------------------
15 years 10 mons 14 days

=# SELECT date_trunc('months', '1 year 2 months 20 days 15 minutes 55 seconds'::interval) as date_trunc_func;
----------------------------------------------
1 year 2 mons

=# SELECT 5 * '2 years 3 months 5 days'::interval as mult;
----------------------------------------------
 11 years 3 mons 25 days
```

**Desktop:**
 - OS: Windows Server 2019 x64  and Windows 10 x64

**ADS:**
- ADS Version 1.45.1 (system setup)
- ADS PostgresSQL extension version 0.5.0 
- PostgreSQL version 13.8, compiled by Visual C++ build 1914, 64-bit

**Additional context**
Date/timestamp datatypes with arithmetic operator `-` produce correct (expected) result, for example:
```sql
SELECT '20100101'::date - '19940215'::date AS diff1;
        diff1
-------------------
       5799

SELECT '20100101'::timestamp - '19940215'::timestamp AS diff2;
        diff2
-------------------
   5799 days, 0:00:00
```

P.S. Probably I should also refer to [pgtoolsservice](https://github.com/microsoft/pgtoolsservice).

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by LSIND** [comment]
I installed extension v0.5.1 (win x64), the results of interval output are as expected. Thank you for your work!

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/15229a8f-69f7-4b7b-9f61-79550f0be0d6)
