### ISSUE TITLE
Once connect to a Azure database, dashboard doesn't open to default database.

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#46]
SQL Ops Version: 0.25.4  (Jan public preview)
PG Extension Version: v1.0.0-alpha.2 

Repro Step: 
(1) Open SQL Ops, connect to Azure Database PG 9.5 (or 9.6) via connection dialog.
Fill in connect info like below:
![image](https://user-images.githubusercontent.com/30940057/35464912-8a112fbe-02ad-11e8-851a-ff57294ca1c7.png)

(2) Click 'Connect'. You will see the dashboard after connection succeed.

Expected: The dashboard should open to default database
![image](https://user-images.githubusercontent.com/30940057/35464865-30b88cc8-02ad-11e8-9b4a-5635f4059e63.png)

Fact: The dashboard stays at server level.
![image](https://user-images.githubusercontent.com/30940057/35464876-4139aa50-02ad-11e8-8f88-60b74e68eeec.png)

Note: this issue only happens on Azure DB.

**Comment by nasc17** [comment]
Can you please install latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
