### ISSUE TITLE
Postgres Projects in Azure Data Studio is not working anymore

### ISSUE THREAD

**Issue by ptorchilov** [microsoft/azuredatastudio-postgresql#461]
**Main issue description**
I'm trying to create a new Postgres Project in Azure Data Studio following [this article](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/introducing-postgres-projects-in-azure-data-studio/ba-p/1330728) and I'm not able to create a .pgproj file.

**To Reproduce**
1. Install Azure Data Studio and PostgreSQL v0.5.0 and SQL Database Projects v1.2.0 (just in case, not necessary)
2. I was following the instructions from the provided article and created new folder
3. Then right-click on folder's area and click on New PostgreSQL Project
4. Noting happened, no errors pgSQLToolsService terminal
5. Also, I was trying to call pgproj.add.new manually and got the popup 'command  'pgproj.add.new' not found'

 - OS - Windows 10

**Additional context**
I think this feature is broken since v0.2.7 version of the plugin. I've installed vsix plugin with the version v0.2.7 manually to Azure Data Studio and everything is working according instructions from the provided article.

**My questions here:**

1. Are you going to make a fix for this functionality?
2. Are you going to support Postgres Project in Azure Data Studio in the future? Right now there is only tables support, no views or stored procedures.

**Comment by nasc17** [comment]
@ptorchilov 

Question 1: Working on fix to be included our next release. Thank you for catching this regression.
Question 2: If you have feature enhancement suggestions for Postgres Project, please file it in our issue tracker :-)

**Comment by ptorchilov** [comment]
Alright, thanks for the reply. I'll create a separate feature request to support more database objects for Postgres Project when it will be fixed in the following release.

**Comment by nasc17** [comment]
Bug has been addressed in our unstable release of PostgreSQL extension [v0.5.1-insiders](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders). We would appreciate your verification that it has been handled appropriately.

**Comment by cputman-impinj** [comment]
I just stumbled upon this problem, and this bug issue, so downloaded the 0.5.1-insiders VSIX and was able to complete the steps that were previously failing from the same article that OP referenced when they logged this bug.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/69922333/0a4fa64a-e67e-4035-9ba5-be284a81b670)
