### ISSUE TITLE
Unable to get results for PostgreSql

### ISSUE THREAD

**Issue by chasmere** [microsoft/azuredatastudio-postgresql#466]
- Azure Data Studio Version: 1.45.1
- OS Version: Windows_NT x64 10.0.22621

![image](https://github.com/microsoft/azuredatastudio/assets/6518250/1adec54e-aa80-4d4b-8128-aab4b904499c)

Steps to Reproduce:

1. Create simple query
2. **Issue**: Result is red None without any issue.

to be
1. **Verify** that you got list of values from table.

![image](https://github.com/microsoft/azuredatastudio/assets/6518250/03c2851a-6072-4ad9-b4e9-42a24340aaa8)

Does this issue occur when all extensions are disabled?: Yes/No
Extension needs to be enabled for PostgeSQL

**Comment by nasc17** [comment]
@chasmere this bug may have been addressed in the unstable release of our extension. Please inform us if same issue presents itself: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.5.1-insiders

Additional error logging you can check:
C:\Users<user_name>\AppData\Roaming\azuredatastudio\logs
(esp. C:\Users\daeunyim\AppData\Roaming\azuredatastudio\logs\exthost1)
C:\Users<user_name>\AppData\Roaming\sqlops\pgsql

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.6.0 and Azure Data Studio v1.47.0. Reopen if this issue is still present, thank you.
