### ISSUE TITLE
Script: Constrain and Primary Key is missing when create table script

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#47]
SQL Ops Version: 0.25.4 (Jan public preview)
PG Extension Version: v1.0.0-alpha.2
PG version: on-prem 9.5, Azure DB for Postgres 9.5, Azure DB for Postgres 9.6

Repro Step: 
(1) Install Pagila DB. (which already install on Azure PG 95 and 96 servers)
(2) Navigate to Table via SQL Ops OE. 
(3) Right click 'public.actor' table, click 'Script as Create'. Generated script is :
![image](https://user-images.githubusercontent.com/30940057/35466789-fbc9f7f4-02bb-11e8-9a24-e03ed67cb8ea.png)

Expected: It should be the same with script generated via PG-Admin4:
![image](https://user-images.githubusercontent.com/30940057/35466809-3e80827a-02bc-11e8-9178-bbae9d815441.png)
Fact: The constrain, index, trigger parts are missing.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.3.1. Please reopen if issue persists, thank you.
