### ISSUE TITLE
Connection: definition of service 'undefined' not found

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#64]
Repro Step:
1. In Connection Dialog, fill in:
![image](https://user-images.githubusercontent.com/30940057/48585684-3983ec00-e8e2-11e8-82b0-319233bcbdc7.png)
2. Click 'Advanced', fillin Port number
![image](https://user-images.githubusercontent.com/30940057/48585712-4f91ac80-e8e2-11e8-85fe-60fd09ae2f6e.png)

Fact: Below window pops up.
![image](https://user-images.githubusercontent.com/30940057/48585640-15280f80-e8e2-11e8-8f55-2aea7761c1f3.png)
Expected: There is no 'service' field, I don't get the error message.

**Comment by swjain23** [comment]
@ChrisSun-ms - The error is happening because the value of Host IP address is set as undefined. It is overriding the service name value and that is why you are getting 'service name is undefined'. Remove undefined from other fields and just set port as 5432 and it should work.
