### ISSUE TITLE
Connection: Request connection/buildconnectioninfo failed.

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#65]
DataStudio Version: 1.2.4 (11/06/2018)
PG Extension Version: v1.0.0-alpha.2

Repro Steps:
1. connect to a DB via Connection dialog. 

Fact: Connection succeed, but there's error msg showed up:
![image](https://user-images.githubusercontent.com/30940057/48585964-33dad600-e8e3-11e8-93ff-19d53f175202.png)
Expected: NO message should shows up

**Comment by swjain23** [comment]
no repro, this has been fixed.
