### ISSUE TITLE
Connection: un-friendly user error message

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#66]
If you don't put in password in connection dialog, below user error message pops out. 
More user friendly message should shows up. 
![image](https://user-images.githubusercontent.com/30940057/48590144-42c98480-e8f3-11e8-9620-a473e1e884d6.png)

**Comment by swjain23** [comment]
This is the message that we get from the PG server and is consistent with what is expected.
