### ISSUE TITLE
OGF - PGSQL - Installation

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#70]
**Installation**  

1. After install VSIX, extension should work well. 'Postgres' option should shows up in Connection dialog.
2. After uninstall VSIX, DataStudio should work well. 'Postgres' option should not shows up in Connection dialog.

## Test on different platforms
- [x] **Test on Windows**
- [x] **Test on Mac**
- [x] **Test on Linux**

**Comment by nasc17** [comment]
Please update to latest stable release of PostgreSQL extension v0.4.2.
