### ISSUE TITLE
Script: Create Function Script mismatches Pg-admin4 result

### ISSUE THREAD

**Issue by ChrisSun-ms** [microsoft/azuredatastudio-postgresql#72]
Data Studio Version: 1.2.4 (Nov/06)

Repro Step:
1. Create function with below script:
CREATE OR REPLACE FUNCTION public.Ran(
	integer,
	integer)
    RETURNS "Ran"
    LANGUAGE 'internal'
    COST 1
    IMMUTABLE 
    ROWS 0
AS $BODY$
range_constructor2
$BODY$;

2. Generate create table script via Data Studio.

Fact: generated script is
![image](https://user-images.githubusercontent.com/30940057/49037681-c004bd00-f16f-11e8-964f-4a102c4d1cd7.png)

Expected: script should match Pg-admin4
![image](https://user-images.githubusercontent.com/30940057/49037721-d3b02380-f16f-11e8-99ba-23c290b77be0.png)

**Comment by spatrickdoyle** [comment]
I am also experiencing this issue with ADS on Windows.

ADS version: `1.29.0.0` and `1.30.0.0`
Postgres extension version: `0.2.7`

If I "Script as create" a function called foobar, the code generated executes and a new function appears in the sidebar called foobar()(), but I am unable to run ALTER or DELETE statements against the created function - it seems that the extra set of parentheses is confusing it.

It seems to me the generated script should look like:

`CREATE FUNCTION public."foobar"()`

or something to that effect which does not add an extra set of parentheses to the name. If I run the above manually it creates the new function as expected. Should be a relatively simple fix?
