### ISSUE TITLE
Unhandled exception while executing query with JSONB field

### ISSUE THREAD

**Issue by wiktor-golonka** [microsoft/azuredatastudio-postgresql#94]
Hi, 
It looks like querying JSONB fields doesn't work right now. 

To recreate:
```
create table testtable (
    data jsonb,
    description text
);

insert into testtable (data, description) values ('{"test":"dd"}', 'test');
```

Running: `select * from testtable;`
will result with error: `Unhandled exception while executing query: 'dict' object has no attribute 'encode'`

Running: `select description from testtable` 
works just fine.

Thanks!

**Comment by tdamsma** [comment]
Ran into this as well. Casting to json does work as expected:

```
select data::json from testtable;
```

**Comment by andershermansen** [comment]
Had the same issue. Implemented this support in the pgtoolsservice
Issue: https://github.com/Microsoft/pgtoolsservice/issues/207
PR: https://github.com/Microsoft/pgtoolsservice/pull/208

**Comment by willsllc** [comment]
@andershermansen -- really interested to use this product, but all our tables use JSONB.... do you have a sense how long it takes for a PR to make it into the product?

**Comment by akamath46297** [comment]
@andershermansen , thanks for the PR. I will take a look.

**Comment by andershermansen** [comment]
@willsllc I don't know, it's not up to me.

@akamath46297 Great, thanks. I have tested it briefly with JSONB on my own database and seems to work fine.

**Comment by AgSync-Aaron** [comment]
I ran into this bug as well. Thanks @andershermansen for a possible fix already.

**Comment by akamath46297** [comment]
https://github.com/Microsoft/pgtoolsservice/pull/208 is now merged into master. We will work on a release plan on this.

**Comment by bwyatt** [comment]
Is there a way to use pre-release versions of the PG Tools Service? My team relies heavily on JSONB, so this is a real pain point for us in adopting Azure Data Studio.

**Comment by wiktor-golonka** [comment]
@bwyatt: You can pull PG Tools Service repository: 
https://github.com/Microsoft/pgtoolsservice

build it:
https://github.com/Microsoft/pgtoolsservice/wiki/How-to-Contribute#building-executables

 and attach it to Azure Data Studio:
https://github.com/Microsoft/pgtoolsservice/wiki/How-to-Contribute#remote-debugging-with-azure-data-studio

And if it doesn't work (which was my case) you can copy all files from:
`\pgtoolsservice\build\exe.win-amd64-3.6` (which should be location of your pgtoolsservice's build)
into: 
`C:\Users\{YOUR_USER}\.azuredatastudio\extensions\microsoft.azuredatastudio-postgresql-0.1.0\out\pgsqltoolsservice\Windows\v1.0.0\pgsqltoolsservice`

I'm not sure though if that's the best way to make it working.

**Comment by bwyatt** [comment]
The last option you listed there worked for me. I'll let the rest of my team know about this. Thanks!

**Comment by akamath46297** [comment]
This should be fixed with https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.2.0
