### ISSUE TITLE
Client Certificate authentication for Postgres

### ISSUE THREAD

**Issue by cocowalla** [Microsoft/azuredatastudio-postgresql#96]
Postgres support client certificate authentication, and login with this method is supported in other client tools such as pgAdmin.

It would be great to see client certificate authentication for Postgres in Azure Data Studio.

**Comment by akamath46297** [comment]
@cocowalla, in connection window of Azure Data Studio we have a way to provide advanced options for connections as shown below where you can provide SSL cert filename and key file name. Is this what you are asking about ? Did you try this ?

![image](https://user-images.githubusercontent.com/30480046/55020715-a4da7a80-4fb4-11e9-8706-658e10df1f83.png)

**Comment by cocowalla** [comment]
I'm not sure if that option wasn't in the version I tried, or if I need to get my sight tested - either way, I see it now, and it's exactly what I was looking for!
