### ISSUE TITLE
On disconnection from the server you get stuck in an error loop

### ISSUE THREAD

**Issue by infraweavers** [microsoft/azuredatastudio-postgresql#99]
Hello,

Using Postgresql against some servers with a firewall between that closes sessions after inactivity so the user gets disconnected periodically.

When this happens the UI gets stuck with an error appearing (see screenshot) and no way to force it work. Refresh doesn't work, disconnect gets stuck with an error "unable to expand node".

![image](https://user-images.githubusercontent.com/36475663/54701699-69136100-4b2d-11e9-9fdc-21d37188e88a.png)

The only way to resolve the sitation is to quit the application and relaunch it.

**Comment by akamath46297** [comment]
@infraweavers , thanks for reporting this issue. We were able to repro this and will apply a fix.

**Comment by swjain23** [comment]
Fixed by https://github.com/microsoft/pgtoolsservice/pull/252
